import { City, Category, Business, Experience, Route, EventItem } from '@/types';

export const ATIBAIA_CITY: City = {
  id: 'city-atibaia',
  name: 'Atibaia',
  slug: 'atibaia',
  state: 'SP',
  country: 'Brasil',
  badge: 'Estância Turística de Atibaia - SP',
  subtitle: 'Natureza, aventura e experiências para viver Atibaia.',
  description: 'Conhecida internacionalmente como a Capital Nacional do Morango e das Flores, Atibaia encanta com o Monumento Natural Estadual da Pedra Grande (1.418m de altitude), clima serrano privilegiado, polo cervejeiro artesanal e hotelaria de alto padrão.',
  image_url: '/images/atibaia/hero.webp',
  hero_image: '/images/atibaia/hero.webp',
  tags: ['Natureza', 'Aventura', 'Gastronomia', 'Família'],
  is_active: true,
};

export const ATIBAIA_CATEGORIES: Category[] = [
  {
    id: 'cat-atibaia-natureza',
    city_id: 'city-atibaia',
    name: 'Natureza & Mirantes',
    slug: 'natureza-mirantes',
    description: 'Pedra Grande, mirantes da Serra da Mantiqueira, parques ecológicos e trilhas arborizadas.',
    icon: 'Mountain',
    image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-aventura',
    city_id: 'city-atibaia',
    name: 'Turismo de Aventura',
    slug: 'turismo-de-aventura',
    description: 'Voo livre e parapente da Pedra Grande, passeios 4x4, arvorismo, tirolesa e escalada.',
    icon: 'Compass',
    image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-restaurantes',
    city_id: 'city-atibaia',
    name: 'Restaurantes & Gastronomia',
    slug: 'restaurantes-cafes',
    description: 'Carnes nobres na parrilla, culinária italiana, comida caipira e cervejarias artesanais.',
    icon: 'Utensils',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-hospedagem',
    city_id: 'city-atibaia',
    name: 'Hospedagem & Resorts',
    slug: 'hospedagem-resorts',
    description: 'Resorts de referência com pensão completa, pousadas boutique e chalés em meio à mata.',
    icon: 'Hotel',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-passeios',
    city_id: 'city-atibaia',
    name: 'Passeios & Família',
    slug: 'passeios-familia',
    description: 'Parque Edmundo Zanoni, teleférico municipal, pedalinhos no Lago do Major e orquidários.',
    icon: 'Bus',
    image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-compras',
    city_id: 'city-atibaia',
    name: 'Compras & Agroturismo',
    slug: 'compras-produtos-locais',
    description: 'Colheita de morangos em estufas, orquídeas raras, doces artesanais e artesanato local.',
    icon: 'ShoppingBag',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
];

export const ATIBAIA_BUSINESSES: Business[] = [
  {
    id: 'biz-atibaia-1',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-aventura',
    name: 'Clube Atibaiense de Voo Livre (CAVL)',
    slug: 'clube-atibaiense-de-voo-livre-cavl',
    description: 'A mais tradicional associação de voo livre de São Paulo. Oferece voos duplos de instrução em parapente e asa-delta saltando da imponente rampa da Pedra Grande (1.418m) com instrutores certificados pela CBVL, fotos e vídeos em 4K e pouso seguro no gramado oficial.',
    address: 'Monumento Natural Estadual da Pedra Grande - Estrada da Pedra Grande, Atibaia - SP',
    phone: '(11) 99876-5432',
    whatsapp: '5511998765432',
    instagram: 'cavl_atibaia',
    website: 'https://voolivreatibaia.com.br',
    latitude: -23.1610,
    longitude: -46.5290,
    price_min: 380,
    price_max: 650,
    opening_hours: 'Sábado e Domingo, das 08h às 18h (sujeito às condições meteorológicas)',
    main_image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.9,
    review_count: 940,
    amenities: ['Instrutores Credenciados CBVL', 'Fotos & Vídeo em 4K', 'Equipamentos Homologados', 'Resgate da Pista de Pouso'],
    tags: ['Voo Livre', 'Parapente', 'Pedra Grande', 'Aventura', 'Adrenalina'],
    images: [
      { id: 'img-at-1-1', business_id: 'biz-atibaia-1', image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=800&q=80', sort_order: 1 },
      { id: 'img-at-1-2', business_id: 'biz-atibaia-1', image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', sort_order: 2 },
    ]
  },
  {
    id: 'biz-atibaia-2',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-compras',
    name: 'Orquidário & Morangos Takebayashi',
    slug: 'orquidario-morangos-takebayashi',
    description: 'Tradição agrícola e turismo rural em Atibaia. Cultivo protegido de orquídeas raras em estufas floridas, colheita de morangos hidropônicos frescos diretamente nos canteiros e cafeteria com tortas, geleias e doces caseiros da fazenda.',
    address: 'Estrada dos Pires, 1200 - Bairro dos Pires, Atibaia - SP',
    phone: '(11) 4416-1234',
    whatsapp: '5511987654321',
    instagram: 'orquidariotakebayashi',
    website: 'https://takebayashi.com.br',
    latitude: -23.1200,
    longitude: -46.5500,
    price_min: 30,
    price_max: 160,
    opening_hours: 'Terça a Domingo, das 09h às 17h',
    main_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.8,
    review_count: 1320,
    amenities: ['Colheita de Morango', 'Estufas de Orquídeas', 'Cafeteria Colonial', 'Pet Friendly', 'Estacionamento Gratuito'],
    tags: ['Morango', 'Orquídeas', 'Agroturismo', 'Família', 'Doces Artesanais'],
    images: [
      { id: 'img-at-2-1', business_id: 'biz-atibaia-2', image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80', sort_order: 1 },
    ]
  },
  {
    id: 'biz-atibaia-3',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-hospedagem',
    name: 'Bourbon Atibaia Resort',
    slug: 'bourbon-atibaia-resort',
    description: 'Um dos resorts mais premiados e estruturados da América Latina, localizado a 50 minutos de São Paulo. Conta com complexo aquático climatizado e aquecido, spa com terapias relaxantes, espaço exclusivo Turma da Mônica, centro gastronômico com diversos restaurantes e área verde de 400 mil m².',
    address: 'Rodovia Fernão Dias, km 37,5 - Jardim Samambaia, Atibaia - SP',
    phone: '(11) 4414-4700',
    whatsapp: '5511976543210',
    instagram: 'bourbonatibaia',
    website: 'https://bourbon.com.br/resort/bourbon-atibaia',
    latitude: -23.1350,
    longitude: -46.5650,
    price_min: 1200,
    price_max: 3400,
    opening_hours: 'Recepção 24 horas',
    main_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.9,
    review_count: 2450,
    amenities: ['Pensão Completa', 'Parque Aquático Aquecido', 'Espaço Turma da Mônica', 'Spa Lazer Completo', 'Quadras de Tênis'],
    tags: ['Resort', 'Família', 'Alto Padrão', 'Piscina Aquecida', 'Lazer'],
  },
  {
    id: 'biz-atibaia-4',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-passeios',
    name: 'Parque Municipal Edmundo Zanoni & Teleférico',
    slug: 'parque-edmundo-zanoni-teleferico',
    description: 'Cartão-postal no centro de Atibaia com lago com pedalinhos, Museu de História Natural, Salão do Artesão, playground arborizado e estação de embarque do Teleférico que liga o parque ao Lago do Major com linda vista panorâmica da cidade.',
    address: 'Av. Horácio Netto, 1030 - Samambaia Parque Residencial, Atibaia - SP',
    phone: '(11) 4414-0400',
    whatsapp: '5511965432109',
    instagram: 'turismoatibaia',
    website: 'https://atibaia.sp.gov.br/turismo',
    latitude: -23.1180,
    longitude: -46.5560,
    price_min: 20,
    price_max: 50,
    opening_hours: 'Terça a Domingo, das 09h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.7,
    review_count: 890,
    amenities: ['Passeio de Teleférico', 'Pedalinhos no Lago', 'Museu de História Natural', 'Feira de Artesanato', 'Lanchonete'],
    tags: ['Parque', 'Teleférico', 'Família', 'Lago', 'Cultura'],
  },
  {
    id: 'biz-atibaia-5',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Cervejaria Freising Haus',
    slug: 'cervejaria-freising-haus',
    description: 'Cervejaria e choperia em autêntico estilo bávaro germânico. Produz chopes artesanais puros malte seguindo a rigorosa Lei de Pureza Alemã de 1516. Serve pratos alemães clássicos como Eisbein (joelho de porco), salsichas alemãs e fondue em biergarten climatizado.',
    address: 'Av. Jerônimo de Camargo, 7860 - Jardim do Lago, Atibaia - SP',
    phone: '(11) 4412-1516',
    whatsapp: '5511954321098',
    instagram: 'freisinghaus',
    website: 'https://freisinghaus.com.br',
    latitude: -23.1100,
    longitude: -46.5400,
    price_min: 55,
    price_max: 180,
    opening_hours: 'Quarta a Domingo, das 12h às 23h30',
    main_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.8,
    review_count: 670,
    amenities: ['Biergarten Alemão', 'Chopes Puros Malte', 'Gastronomia Bávara', 'Música Alemã & Rock', 'Espaço Pet Friendly'],
    tags: ['Cervejaria', 'Chope Artesanal', 'Comida Alemã', 'Biergarten', 'Noite'],
  },
  {
    id: 'biz-atibaia-6',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-restaurantes',
    name: 'San Costilla Carnes Especiais',
    slug: 'san-costilla-carnes-especiais',
    description: 'A casa de carnes de referência na badalada Alameda Lucas Nogueira Garcez. Cortes nobres Angus preparados na parrilla aberta, bife de ancho, picanha premium, hambúrgueres artesanais na brasa e excelente carta de vinhos e cervejas artesanais.',
    address: 'Alameda Lucas Nogueira Garcez, 2574 - Jardim Paulista, Atibaia - SP',
    phone: '(11) 4411-8899',
    whatsapp: '5511943210987',
    instagram: 'sancostillaatibaia',
    website: 'https://sancostilla.com.br',
    latitude: -23.1310,
    longitude: -46.5620,
    price_min: 80,
    price_max: 260,
    opening_hours: 'Segunda a Domingo, das 11h30 às 23h',
    main_image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.9,
    review_count: 520,
    amenities: ['Cortes Angus', 'Parrilla Uruguaia', 'Adega Climatizada', 'Ambiente Climatizado', 'Estacionamento com Manobrista'],
    tags: ['Parrilla', 'Carnes Nobres', 'Alameda Lucas', 'Gastronomia', 'Vinho'],
  },
  {
    id: 'biz-atibaia-7',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Romano Restaurante & Pizzaria',
    slug: 'romano-restaurante-pizzaria',
    description: 'Pizzas artesanais de massa de fermentação lenta de 48h assadas em forno a lenha napolitano, além de massas frescas feitas diariamente à mão, risotos cremosos e sobremesas italianas como o autêntico Tiramisù.',
    address: 'Alameda Lucas Nogueira Garcez, 1980 - Jardim Paulista, Atibaia - SP',
    phone: '(11) 4412-5500',
    whatsapp: '5511932109876',
    instagram: 'romanopizzariaatibaia',
    website: 'https://romanopizzaria.com.br',
    latitude: -23.1280,
    longitude: -46.5600,
    price_min: 60,
    price_max: 160,
    opening_hours: 'Terça a Domingo, das 18h30 às 23h30',
    main_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: false,
    is_premium: false,
    rating: 4.8,
    review_count: 410,
    amenities: ['Forno a Lenha', 'Fermentação Lenta', 'Carta de Vinhos', 'Ambiente Romântico'],
    tags: ['Pizza', 'Italiano', 'Forno a Lenha', 'Massa Caseira', 'Jantar'],
  },
  {
    id: 'biz-atibaia-8',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Cervejaria Los Compadres Brewpub',
    slug: 'cervejaria-los-compadres-brewpub',
    description: 'Brewpub premiado em Atibaia com 14 torneiras de chope artesanal produzidos no próprio local: IPAs aromáticas, Sours refrescantes, Lagers leves e Stouts encorpadas, combinadas com petiscos de boteco de alto nível e música ao vivo.',
    address: 'Av. Joviano Alvim, 1370 - Atibaia Jardim, Atibaia - SP',
    phone: '(11) 4413-2211',
    whatsapp: '5511921098765',
    instagram: 'loscompadrescervejaria',
    website: 'https://loscompadres.com.br',
    latitude: -23.1220,
    longitude: -46.5490,
    price_min: 40,
    price_max: 130,
    opening_hours: 'Quinta a Domingo, das 17h às 00h',
    main_image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    rating: 4.7,
    review_count: 360,
    amenities: ['14 Torneiras On Tap', 'Fábrica à Vista', 'Hambúrgueres Artesanais', 'Música ao Vivo'],
    tags: ['Cervejaria', 'Craft Beer', 'IPA', 'Brewpub', 'Happy Hour'],
  },
  {
    id: 'biz-atibaia-9',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-hospedagem',
    name: 'Pousada Refúgio do Saci',
    slug: 'pousada-refugio-do-saci',
    description: 'Pousada de montanha ecológica cercada por nascentes e mata nativa preservada. Chalés rústicos em madeira com lareira, hidromassagem, trilhas para caminhadas meditativas e café da manhã colonial com produtos orgânicos da região.',
    address: 'Estrada dos Pires, 1800 - Portão, Atibaia - SP',
    phone: '(11) 4416-8900',
    whatsapp: '5511910987654',
    instagram: 'pousadarefugiodosaci',
    website: 'https://refugiodosaci.com.br',
    latitude: -23.1400,
    longitude: -46.5700,
    price_min: 390,
    price_max: 850,
    opening_hours: 'Check-in a partir das 14h / Check-out até às 12h',
    main_image_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    rating: 4.9,
    review_count: 280,
    amenities: ['Chalés com Lareira', 'Banheira de Hidro', 'Piscina Natural', 'Café da Manhã Orgânico'],
    tags: ['Pousada', 'Ecoturismo', 'Casal', 'Natureza', 'Sossegado'],
  },
  {
    id: 'biz-atibaia-10',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-natureza',
    name: 'Monumento Natural Estadual da Pedra Grande',
    slug: 'monumento-natural-pedra-grande-atibaia',
    description: 'O símbolo máximo de Atibaia e um dos maiores monólitos rochosos do Brasil. Situado a 1.418 metros de altitude em área de preservação ambiental, proporciona uma vista de 360° para a Serra da Mantiqueira e diversas cidades da região, sendo o local preferido para contemplar o nascer e o pôr do sol.',
    address: 'Acesso pela Estrada da Pedra Grande, s/n - Atibaia - SP',
    phone: '(11) 4412-2884',
    whatsapp: '5511988882884',
    instagram: 'pedragrandeatibaia',
    website: 'https://pedragrande.sp.gov.br',
    latitude: -23.1610,
    longitude: -46.5290,
    price_min: 0,
    price_max: 0,
    opening_hours: 'Aberto diariamente das 08h30 às 17h30',
    main_image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 5.0,
    review_count: 3200,
    amenities: ['Mirante Panorâmico 360°', 'Ponto de Decolagem de Voo Livre', 'Trilhas Ecológicas', 'Guarita e Controle de Acesso'],
    tags: ['Mirante', 'Pedra Grande', 'Pôr do Sol', 'Natureza', 'Mantiqueira'],
  },
];

export const ATIBAIA_EXPERIENCES: Experience[] = [
  {
    id: 'exp-atibaia-1',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-1',
    category_id: 'cat-atibaia-aventura',
    name: 'Voo Duplo de Parapente com Instrutor na Pedra Grande',
    slug: 'voo-duplo-parapente-pedra-grande-atibaia',
    description: 'Decole a 1.418 metros de altitude no cartão-postal de Atibaia e sobrevoe vales verdejantes, montanhas e lagos com um instrutor experiente credenciado pela CBVL. A experiência inclui instrução de segurança, equipamento completo, filmagem e fotos em alta definição com câmera GoPro 4K e resgate ao ponto de encontro.',
    price: 450,
    duration: '2h00 (voo de 15 a 25 min)',
    main_image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    included: [
      'Voo de 15 a 25 minutos com piloto instrutor credenciado',
      'Equipamentos de voo homologados e revisados',
      'Fotos e vídeos em alta definição gravados com GoPro 4K',
      'Translado de retorno do pouso para o ponto de apoio',
    ],
  },
  {
    id: 'exp-atibaia-2',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-2',
    category_id: 'cat-atibaia-compras',
    name: 'Colheita de Morangos nas Estufas & Degustação Colonial',
    slug: 'colheita-de-morangos-takebayashi',
    description: 'Passeio guiado pelas estufas elevadas de morangos em Atibaia, onde você colhe seus próprios morangos frescos e doces direto do pé para levar para casa. Em seguida, desfrute de um café da tarde na cafeteria da fazenda com taça de morango com chantilly e suco natural.',
    price: 65,
    duration: '1h30',
    main_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    included: [
      'Acesso livre às estufas e instrução de colheita',
      '1 cesta de 500g de morangos colhidos por você',
      'Taça especial de morango com chantilly artesanal',
      'Visita guiada ao orquidário com espécies raras',
    ],
  },
  {
    id: 'exp-atibaia-3',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-5',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Tour Cervejeiro & Degustação Harmonizada no Freising Haus',
    slug: 'tour-cervejeiro-freising-haus',
    description: 'Visita técnica pelos tanques de fermentação da cervejaria bávara em Atibaia com mestre-cervejeiro, conhecendo os segredos da Lei de Pureza de 1516, seguida de degustação guiada de 4 estilos de chopes harmonizados com petiscos alemães.',
    price: 85,
    duration: '1h45',
    main_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    included: [
      'Visita técnica à fábrica com mestre cervejeiro',
      'Degustação de 4 chopes artesanais frescos (150ml cada)',
      'Tábua de degustação com salsichas alemãs e mostardas',
      'Copo de chope exclusivo da cervejaria de brinde',
    ],
  },
];

export const ATIBAIA_ROUTES: Route[] = [
  {
    id: 'route-atibaia-1',
    city_id: 'city-atibaia',
    name: 'Roteiro Clássico: Pedra Grande, Parque Zanoni e Sabores da Alameda',
    slug: 'roteiro-classico-pedra-grande-atibaia',
    description: 'O roteiro indispensável para quem visita Atibaia em 1 dia. Comece a manhã nos ares da Pedra Grande, passeie pelo arborizado Parque Zanoni e finalize a noite com a melhor gastronomia na Alameda Lucas.',
    duration: '1 Dia Completo',
    profile: 'Aventura & Gastronomia',
    image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'ri-at-1-1',
        route_id: 'route-atibaia-1',
        business_id: 'biz-atibaia-10',
        title: '09h00 - Mirante e Caminhada no Cume da Pedra Grande',
        description: 'Subida à Pedra Grande para contemplar a vista panorâmica de 360°, ver os voos de parapente e tirar fotos inesquecíveis.',
        sort_order: 1,
      },
      {
        id: 'ri-at-1-2',
        route_id: 'route-atibaia-1',
        business_id: 'biz-atibaia-2',
        title: '12h30 - Colheita de Morangos e Almoço Rural no Takebayashi',
        description: 'Colha morangos frescos direto na estufa e aprecie pratos caseiros e doces da fazenda.',
        sort_order: 2,
      },
      {
        id: 'ri-at-1-3',
        route_id: 'route-atibaia-1',
        business_id: 'biz-atibaia-4',
        title: '15h30 - Parque Edmundo Zanoni & Passeio de Teleférico',
        description: 'Caminhe ao redor do lago, visite o museu e pegue o teleférico com vista para o Lago do Major.',
        sort_order: 3,
      },
      {
        id: 'ri-at-1-4',
        route_id: 'route-atibaia-1',
        business_id: 'biz-atibaia-6',
        title: '19h30 - Jantar na Parrilla do San Costilla na Alameda Lucas',
        description: 'Feche o dia com cortes nobres angus preparados na brasa e excelente vinho na principal avenida gastronômica.',
        sort_order: 4,
      },
    ],
  },
  {
    id: 'route-atibaia-2',
    city_id: 'city-atibaia',
    name: 'Circuito Cervejeiro & Gastronomia Noturna de Atibaia',
    slug: 'circuito-cervejeiro-atibaia',
    description: 'Um itinerário vespertino e noturno para os amantes de boas cervejas artesanais, música ao vivo e ambientes descontraídos em Atibaia.',
    duration: 'Tarde / Noite',
    profile: 'Jovens & Amigos',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'ri-at-2-1',
        route_id: 'route-atibaia-2',
        business_id: 'biz-atibaia-5',
        title: '16h00 - Biergarten na Cervejaria Freising Haus',
        description: 'Degustação de chopes artesanais bávaros e petiscos alemães em ambiente ao ar livre.',
        sort_order: 1,
      },
      {
        id: 'ri-at-2-2',
        route_id: 'route-atibaia-2',
        business_id: 'biz-atibaia-8',
        title: '19h30 - Torneiras Artesanais & Burgers no Los Compadres',
        description: 'Variedade de IPAs e cervejas especiais com hambúrgueres artesanais na brasa.',
        sort_order: 2,
      },
    ],
  },
];

export const ATIBAIA_EVENTS: EventItem[] = [
  {
    id: 'evt-atibaia-1',
    city_id: 'city-atibaia',
    name: '44ª Festa das Flores e do Morango de Atibaia 2026',
    title: '44ª Festa das Flores e do Morango de Atibaia 2026',
    slug: 'festa-flores-morango-atibaia-2026',
    description: 'O maior e mais aguardado evento cultural e gastronômico de Atibaia. Pavilhões ornamentados com milhares de flores e orquídeas, estandes com as melhores variedades de morangos, culinária japonesa e internacional, shows culturais de taiko e dança folclórica no Parque Zanoni.',
    event_date: '2026-09-04',
    start_date: '2026-09-04',
    end_date: '2026-09-27',
    event_time: 'Sextas, Sábados e Domingos, das 09h às 18h',
    location: 'Parque Municipal Edmundo Zanoni - Av. Horácio Netto, 1030, Atibaia - SP',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'evt-atibaia-2',
    city_id: 'city-atibaia',
    name: 'Festival de Inverno & Circuito Gastronômico de Atibaia',
    title: 'Festival de Inverno & Circuito Gastronômico de Atibaia',
    slug: 'festival-inverno-gastronomia-atibaia-2026',
    description: 'Festival de inverno reunindo os principais restaurantes da Alameda Lucas Nogueira Garcez com pratos exclusivos de fondue, caldos da serra, carnes nobres e chopes artesanais, além de apresentações de jazz e MPB.',
    event_date: '2026-07-10',
    start_date: '2026-07-10',
    end_date: '2026-08-02',
    event_time: 'A partir das 19h00',
    location: 'Alameda Lucas Nogueira Garcez, Atibaia - SP',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
];
