import { City, Category, Business, Experience, Route, EventItem } from '@/types';

export const ATIBAIA_CITY: City = {
  id: 'city-atibaia',
  name: 'Atibaia',
  slug: 'atibaia',
  state: 'SP',
  country: 'Brasil',
  badge: 'Estância Turística de Atibaia - SP',
  subtitle: 'Natureza, aventura e experiências para viver Atibaia.',
  description: 'Natureza, aventura, gastronomia e experiências para aproveitar em qualquer época. Conhecida pelo Monumento Natural da Pedra Grande, clima agradável da serra, festivais do morango e flores e turismo de aventura.',
  tags: ['Natureza', 'Aventura', 'Gastronomia', 'Família'],
  image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',
  hero_image: '/images/atibaia/hero.webp',
  is_active: true,
};

export const ATIBAIA_CATEGORIES: Category[] = [
  {
    id: 'cat-atibaia-natureza',
    city_id: 'city-atibaia',
    name: 'Natureza & Mirantes',
    slug: 'natureza-mirantes',
    description: 'Pedra Grande, mirantes da Serra da Mantiqueira, parques ecológicos e trilhas arborizadas.',
    icon: 'Mountain',
    image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-aventura',
    city_id: 'city-atibaia',
    name: 'Turismo de Aventura',
    slug: 'turismo-de-aventura',
    description: 'Voo livre e parapente da Pedra Grande, arvorismo, tirolesa, passeios 4x4 e escalada.',
    icon: 'Compass',
    image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-restaurantes',
    city_id: 'city-atibaia',
    name: 'Restaurantes & Cafés',
    slug: 'restaurantes-cafes',
    description: 'Gastronomia da serra, cafés coloniais, comida caipira na fazenda, pizzarias e cervejarias artesanais.',
    icon: 'Utensils',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-hospedagem',
    city_id: 'city-atibaia',
    name: 'Hospedagem & Resorts',
    slug: 'hospedagem-resorts',
    description: 'Hotéis fazenda, resorts com infraestrutura completa, pousadas de montanha e chalés românticos.',
    icon: 'Hotel',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-passeios',
    city_id: 'city-atibaia',
    name: 'Passeios & Família',
    slug: 'passeios-familia',
    description: 'Parque Edmundo Zanoni, teleférico municipal, fazendinhas interativas e passeios de trenzinho.',
    icon: 'Bus',
    image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-compras',
    city_id: 'city-atibaia',
    name: 'Compras & Produtos Locais',
    slug: 'compras-produtos-locais',
    description: 'Morangos frescos, doces caseiros, cachaças artesanais, flores ornamentais e feiras de artesanato.',
    icon: 'ShoppingBag',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-guias',
    city_id: 'city-atibaia',
    name: 'Guias Turísticos & Ecoturismo',
    slug: 'guias-ecoturismo',
    description: 'Condutores ambientais credenciados para caminhadas na serra e voos de instrução.',
    icon: 'Compass',
    image_url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-atibaia-cultura',
    city_id: 'city-atibaia',
    name: 'Cultura & Eventos',
    slug: 'cultura-eventos',
    description: 'Festa das Flores e do Morango, casarões históricos, museus municipais e centros culturais.',
    icon: 'Landmark',
    image_url: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
];

export const ATIBAIA_BUSINESSES: Business[] = [
  {
    id: 'biz-atibaia-1',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-aventura',
    name: 'Escola de Voo Livre Pedra Grande (DEMO)',
    slug: 'escola-voo-livre-pedra-grande-demo',
    description: 'Experiência inesquecível de voo duplo de instrução em parapente e asa-delta saltando do topo da famosa Pedra Grande de Atibaia com pilotos credenciados pela CBVL e equipamentos de última geração.',
    address: 'Monumento Natural Estadual da Pedra Grande, Atibaia - SP',
    phone: '(11) 99876-5432',
    whatsapp: '5511998765432',
    instagram: 'voolivrepedragrande',
    website: 'https://voolivreatibaia.com.br',
    latitude: -23.1610,
    longitude: -46.5290,
    price_min: 350,
    price_max: 600,
    opening_hours: 'Sábado e Domingo, das 08h às 18h (condicionado ao clima)',
    main_image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.9,
    review_count: 940,
    amenities: ['Instrutores Credenciados', 'Fotos & Vídeo em 4K', 'Equipamentos Certificados', 'Estacionamento no Cume'],
    tags: ['Voo Livre', 'Parapente', 'Pedra Grande', 'Aventura', 'Adrenalina'],
    gallery: [
      { id: 'img-at-1-1', business_id: 'biz-atibaia-1', image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=800&q=80', sort_order: 1 },
      { id: 'img-at-1-2', business_id: 'biz-atibaia-1', image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', sort_order: 2 },
    ]
  },
  {
    id: 'biz-atibaia-2',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Restaurante & Fazenda do Morango (DEMO)',
    slug: 'restaurante-fazenda-do-morango-demo',
    description: 'Imersão no turismo rural com almoço servido no fogão a lenha, colheita de morangos orgânicos diretamente das estufas suspensas, sobremesas artesanais e ampla área verde para toda a família.',
    address: 'Estrada das Pitas, km 3 - Estância de Atibaia - SP',
    phone: '(11) 4412-3344',
    whatsapp: '5511987654321',
    instagram: 'fazendadomorangoatibaia',
    website: 'https://fazendadomorango.com.br',
    latitude: -23.1200,
    longitude: -46.5500,
    price_min: 70,
    price_max: 190,
    opening_hours: 'Quarta a Domingo, das 11h às 17h',
    main_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.8,
    review_count: 1320,
    amenities: ['Colheita de Morango', 'Playground', 'Pet Friendly', 'Estacionamento Gratuito', 'Empório Rural'],
    tags: ['Morango', 'Comida da Fazenda', 'Família', 'Fogão a Lenha', 'Natureza'],
    gallery: [
      { id: 'img-at-2-1', business_id: 'biz-atibaia-2', image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80', sort_order: 1 },
    ]
  },
  {
    id: 'biz-atibaia-3',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-hospedagem',
    name: 'Resort & Spa Serra de Atibaia (DEMO)',
    slug: 'resort-spa-serra-de-atibaia-demo',
    description: 'Resort de alto padrão cercado por montanhas verdejantes. Piscinas aquecidas cobertas e ao ar livre, quadras poliesportivas, spa completo, recreação monitorada e gastronomia internacional em pensão completa.',
    address: 'Alameda Lucas Nogueira Garcez, 3500 - Atibaia - SP',
    phone: '(11) 4414-9000',
    whatsapp: '5511976543210',
    instagram: 'resortserraatibaia',
    website: 'https://resortserraatibaia.com.br',
    latitude: -23.1350,
    longitude: -46.5650,
    price_min: 650,
    price_max: 1800,
    opening_hours: 'Recepção 24 horas',
    main_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.9,
    review_count: 1150,
    amenities: ['Pensão Completa', 'Piscinas Aquecidas', 'Spa & Massagem', 'Quadras de Tênis', 'Recreação Infantil'],
    tags: ['Resort', 'Família', 'Spa', 'Piscina', 'Montanha'],
  },
  {
    id: 'biz-atibaia-4',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-passeios',
    name: 'Parque Edmundo Zanoni & Teleférico (DEMO)',
    slug: 'parque-edmundo-zanoni-teleferico-demo',
    description: 'Cartão-postal no coração de Atibaia com lago de pedalinhos, Museu de História Natural, salão das festas do morango, playground arborizado e estação de embarque do teleférico com vista panorâmica para o lago do Major.',
    address: 'Av. Horácio Netto, 1030 - Samambaia Park, Atibaia - SP',
    phone: '(11) 4414-0400',
    whatsapp: '5511965432109',
    instagram: 'parquezanoniatibaia',
    website: 'https://turismo.atibaia.sp.gov.br',
    latitude: -23.1180,
    longitude: -46.5490,
    price_min: 15,
    price_max: 30,
    opening_hours: 'Terça a Domingo, das 09h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.7,
    review_count: 2450,
    amenities: ['Passeio de Teleférico', 'Pedalinhos', 'Museu de História', 'Área Verde', 'Acessibilidade'],
    tags: ['Teleférico', 'Parque', 'Família', 'Passeio', 'Lago'],
  },
  {
    id: 'biz-atibaia-5',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-natureza',
    name: 'Monumento Natural da Pedra Grande (DEMO)',
    slug: 'monumento-pedra-grande-demo',
    description: 'Formação rochosa monumental a 1.418 metros de altitude, considerada patrimônio geológico de São Paulo. Ponto de encontro para contemplação do pôr do sol, astrofotografia, trilhas e decolagem de voo livre com visão de 360 graus.',
    address: 'Acesso pela Estrada da Pedra Grande, s/n - Atibaia - SP',
    phone: '(11) 4411-7910',
    whatsapp: '5511954321098',
    instagram: 'pedragrandeoficial',
    website: 'https://guiaturismo.atibaia.sp.gov.br',
    latitude: -23.1630,
    longitude: -46.5280,
    price_min: 0,
    price_max: 0,
    opening_hours: 'Diariamente das 07h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'free',
    is_featured: true,
    is_premium: false,
    rating: 5.0,
    review_count: 3890,
    amenities: ['Entrada Gratuita', 'Mirante 360°', 'Pôr do Sol Mágico', 'Trilhas Sinalizadas'],
    tags: ['Pedra Grande', 'Mirante', 'Pôr do Sol', 'Natureza', 'Trilha'],
  },
  {
    id: 'biz-atibaia-6',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Cervejaria Mantiqueira Artesanal (DEMO)',
    slug: 'cervejaria-mantiqueira-demo',
    description: 'Brewpub com fábrica envidraçada, jardim com mesas ao ar livre, petiscos da serra, hambúrgueres artesanais e torneiras servindo IPAs, Weisses e cervejas maturadas com morangos frescos da região.',
    address: 'Av. Santana, 880 - Jardim Nova Gardênia, Atibaia - SP',
    phone: '(11) 4413-5566',
    whatsapp: '5511943210987',
    instagram: 'cervejamantiqueira',
    website: 'https://cervejariamanqueira.com.br',
    latitude: -23.1250,
    longitude: -46.5580,
    price_min: 45,
    price_max: 130,
    opening_hours: 'Quinta a Domingo, das 17h às 23h30',
    main_image_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.8,
    review_count: 780,
    amenities: ['Música ao Vivo', 'Pet Friendly', 'Tour na Fábrica', 'Estacionamento Próprio'],
    tags: ['Cerveja Artesanal', 'Chopp', 'Música', 'Gastronomia', 'Jardim'],
  },
  {
    id: 'biz-atibaia-7',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-hospedagem',
    name: 'Pousada Mirante da Pedra (DEMO)',
    slug: 'pousada-mirante-da-pedra-demo',
    description: 'Chalés românticos com banheira de hidromassagem dupla e lareira, integrados à mata atlântica com vista panorâmica frontal para o maciço da Pedra Grande. Café da manhã artesanal servido sem pressa.',
    address: 'Estrada do Lázaro, 420 - Atibaia - SP',
    phone: '(11) 4418-2200',
    whatsapp: '5511932109876',
    instagram: 'pousadamirantedapedra',
    website: 'https://pousadamirantedapedra.com.br',
    latitude: -23.1550,
    longitude: -46.5350,
    price_min: 380,
    price_max: 890,
    opening_hours: 'Recepção das 08h às 22h',
    main_image_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: false,
    is_premium: false,
    rating: 4.9,
    review_count: 510,
    amenities: ['Hidromassagem com Vista', 'Lareira', 'Café da Manhã Colonial', 'Wi-Fi', 'Trilha Privativa'],
    tags: ['Pousada Romântica', 'Chalé', 'Casal', 'Pedra Grande', 'Serra'],
  },
  {
    id: 'biz-atibaia-8',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-compras',
    name: 'Empório dos Morangos & Sabores da Serra (DEMO)',
    slug: 'emporio-dos-morangos-atibaia-demo',
    description: 'Espaço tradicional com caixas de morangos recém-colhidos, geleias caseiras, compotas, cachaças premiadas envelhecidas em tonéis de carvalho e orquídeas dos melhores produtores locais.',
    address: 'Rodovia Fernão Dias, km 44 - Atibaia - SP',
    phone: '(11) 4411-8899',
    whatsapp: '5511921098765',
    instagram: 'emporiodosmorangos.atibaia',
    website: 'https://emporiodosmorangos.com.br',
    latitude: -23.1100,
    longitude: -46.5400,
    price_min: 20,
    price_max: 160,
    opening_hours: 'Diariamente das 08h às 19h',
    main_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    rating: 4.7,
    review_count: 620,
    amenities: ['Degustação de Geleias', 'Cafeteria', 'Embalagens Térmicas', 'Estacionamento Fácil'],
    tags: ['Morango', 'Geleia', 'Doces', 'Cachaça', 'Souvenirs'],
  },
  {
    id: 'biz-atibaia-9',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-guias',
    name: 'Ecoturismo & Trekking Mantiqueira (DEMO)',
    slug: 'ecoturismo-trekking-mantiqueira-demo',
    description: 'Expedições a pé e passeios em veículos 4x4 por trilhas secretas da Serra de Atibaia, incluindo a Trilha dos Tropeiros, Trilha da Mineração e travessia com banho de cachoeira.',
    address: 'Praça da Matriz, 45 - Centro Histórico, Atibaia - SP',
    phone: '(11) 4412-7711',
    whatsapp: '5511910987654',
    instagram: 'ecoturismomantiqueira',
    website: 'https://ecoturismomantiqueira.com.br',
    latitude: -23.1170,
    longitude: -46.5520,
    price_min: 60,
    price_max: 220,
    opening_hours: 'Agendamento prévio todos os dias',
    main_image_url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.9,
    review_count: 340,
    amenities: ['Condutores Ambientais', 'Seguro Aventura Incluso', 'Kit Lanche de Trilha', 'Passeios 4x4'],
    tags: ['Trilha', 'Ecoturismo', 'Cachoeira', '4x4', 'Guias'],
  },
  {
    id: 'biz-atibaia-10',
    city_id: 'city-atibaia',
    category_id: 'cat-atibaia-cultura',
    name: 'Centro Cultural & Casarão Julia Ferraz (DEMO)',
    slug: 'casarao-julia-ferraz-demo',
    description: 'Edificação colonial histórica tombada de 1776 no coração de Atibaia. Apresentações de choro, exposições de artes plásticas, memória ferroviária e visitas mediadas pelo patrimônio da cidade.',
    address: 'Rua José Lucas, 11 - Centro, Atibaia - SP',
    phone: '(11) 4412-1200',
    whatsapp: '5511909876543',
    instagram: 'casaraojuliaferraz',
    website: 'https://casaraojuliaferraz.org.br',
    latitude: -23.1160,
    longitude: -46.5530,
    price_min: 0,
    price_max: 20,
    opening_hours: 'Quarta a Domingo, das 10h às 17h',
    main_image_url: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    rating: 4.8,
    review_count: 290,
    amenities: ['Entrada Gratuita ou Contribuição', 'Visita Mediada', 'Café Cultural', 'Eventos de Música'],
    tags: ['Patrimônio', 'História Colonial', 'Música', 'Exposições'],
  },
];

export const ATIBAIA_EXPERIENCES: Experience[] = [
  {
    id: 'exp-atibaia-1',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-1',
    category_id: 'cat-atibaia-aventura',
    name: 'Voo Duplo de Instrução de Parapente na Pedra Grande (DEMO)',
    slug: 'voo-duplo-parapente-pedra-grande-demo',
    description: 'Decole da rampa natural da Pedra Grande a mais de 1.400 metros de altitude e sobrevoe os vales da Mantiqueira em um voo suave e panorâmico gravado em vídeo 4K.',
    price: 380,
    duration: '1h 30min (20min de voo)',
    main_image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'exp-atibaia-2',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-2',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Colheita de Morangos & Degustação Colonial na Fazenda (DEMO)',
    slug: 'colheita-morangos-degustacao-colonial-demo',
    description: 'Passeio guiado pelas estufas de morango onde você colhe sua própria cesta de frutas doces e saboreia café colonial com bolos quentes e geleias artesanais.',
    price: 95,
    duration: '2h 30min',
    main_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'exp-atibaia-3',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-5',
    category_id: 'cat-atibaia-natureza',
    name: 'Trilha Guiada ao Pôr do Sol no Cume da Pedra Grande (DEMO)',
    slug: 'trilha-sunset-pedra-grande-demo',
    description: 'Caminhada ecológica pela trilha histórica com condutor ambiental até o cume rochoso para celebrar o pôr do sol com lanche de serra.',
    price: 65,
    duration: '3h',
    main_image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'exp-atibaia-4',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-4',
    category_id: 'cat-atibaia-passeios',
    name: 'Circuito Teleférico, Pedalinho & Parque Zanoni em Família (DEMO)',
    slug: 'circuito-teleferico-parque-zanoni-demo',
    description: 'Dia completo de lazer com ingresso do teleférico sobre o lago do Major, passeio de pedalinho no lago e visita ao Museu de História Natural.',
    price: 55,
    duration: '3h',
    main_image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: false,
  },
  {
    id: 'exp-atibaia-5',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-6',
    category_id: 'cat-atibaia-restaurantes',
    name: 'Degustação Harmonizada de Cervejas Artesanais da Serra (DEMO)',
    slug: 'degustacao-cervejas-artesanais-serra-demo',
    description: 'Mestre cervejeiro conduz uma degustação de 5 estilos de cervejas artesanais produzidas com água da Mantiqueira, harmonizadas com tábuas de queijos e embutidos locais.',
    price: 110,
    duration: '1h 45min',
    main_image_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
];

export const ATIBAIA_ROUTES: Route[] = [
  {
    id: 'route-atibaia-1',
    city_id: 'city-atibaia',
    name: 'Atibaia em 1 Dia: O Clássico (DEMO)',
    slug: 'atibaia-em-1-dia-classico-demo',
    description: 'O melhor de Atibaia em um dia: teleférico matinal, almoço de fazenda com morangos frescos e pôr do sol inesquecível na Pedra Grande.',
    duration: '1 dia (09h às 18h30)',
    profile: 'Casal / Família / Geral',
    image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-at-1',
        route_id: 'route-atibaia-1',
        business_id: 'biz-atibaia-4',
        title: 'Manhã no Parque Edmundo Zanoni e Teleférico',
        description: 'Passeio agradável pelos jardins floridos, lago e vista panorâmica no teleférico.',
        sort_order: 1,
      },
      {
        id: 'ri-at-2',
        route_id: 'route-atibaia-1',
        business_id: 'biz-atibaia-2',
        title: 'Almoço na Fazenda do Morango',
        description: 'Comida da roça no fogão a lenha e colheita de morangos frescos de sobremesa.',
        sort_order: 2,
      },
      {
        id: 'ri-at-3',
        route_id: 'route-atibaia-1',
        business_id: 'biz-atibaia-5',
        title: 'Pôr do Sol no Cume da Pedra Grande',
        description: 'Subida para assistir ao espetáculo do entardecer sobre a serra.',
        sort_order: 3,
      },
    ]
  },
  {
    id: 'route-atibaia-2',
    city_id: 'city-atibaia',
    name: 'Natureza e Aventura na Serra (DEMO)',
    slug: 'natureza-aventura-na-serra-demo',
    description: 'Para quem busca adrenalina, ar puro e trilhas: voo livre de parapente, trekking e cervejas artesanais.',
    duration: '1 dia (08h às 19h)',
    profile: 'Aventura / Adrenalina / Jovens',
    image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-at-4',
        route_id: 'route-atibaia-2',
        business_id: 'biz-atibaia-1',
        title: 'Voo Livre Saltando da Pedra Grande',
        description: 'Voo duplo emocionante sobre o vale com registro em vídeo 4K.',
        sort_order: 1,
      },
      {
        id: 'ri-at-5',
        route_id: 'route-atibaia-2',
        business_id: 'biz-atibaia-9',
        title: 'Trekking Ecológico na Mantiqueira',
        description: 'Trilha guiada com paradas para banho em riachos cristalinos.',
        sort_order: 2,
      },
      {
        id: 'ri-at-6',
        route_id: 'route-atibaia-2',
        business_id: 'biz-atibaia-6',
        title: 'Happy Hour na Cervejaria Mantiqueira',
        description: 'Chopp artesanal gelado no jardim ao pôr do sol.',
        sort_order: 3,
      },
    ]
  },
  {
    id: 'route-atibaia-3',
    city_id: 'city-atibaia',
    name: 'Atibaia para Famílias & Crianças (DEMO)',
    slug: 'atibaia-para-familias-demo',
    description: 'Roteiro seguro, divertido e leve com fazendinha, pedalinho, teleférico e doces artesanais.',
    duration: '1 dia (10h às 17h)',
    profile: 'Famílias com Crianças',
    image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-at-7',
        route_id: 'route-atibaia-3',
        business_id: 'biz-atibaia-4',
        title: 'Manhã no Parque Zanoni',
        description: 'Playground sombreado, pedalinhos e Museu dos Animais.',
        sort_order: 1,
      },
      {
        id: 'ri-at-8',
        route_id: 'route-atibaia-3',
        business_id: 'biz-atibaia-2',
        title: 'Almoço e Colheita na Fazenda',
        description: 'Crianças colhem morango no pé e brincam na fazendinha.',
        sort_order: 2,
      },
    ]
  },
  {
    id: 'route-atibaia-4',
    city_id: 'city-atibaia',
    name: 'Fim de Semana Romântico na Serra (DEMO)',
    slug: 'fim-de-semana-romantico-atibaia-demo',
    description: 'Dois dias de aconchego com chalé com hidromassagem, jantares românticos e vistas da Mantiqueira.',
    duration: '2 dias (Sábado e Domingo)',
    profile: 'Casais / Romance',
    image_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-at-9',
        route_id: 'route-atibaia-4',
        business_id: 'biz-atibaia-7',
        title: 'Hospedagem na Pousada Mirante da Pedra',
        description: 'Check-in no chalé com hidromassagem e vista para a montanha.',
        sort_order: 1,
      },
      {
        id: 'ri-at-10',
        route_id: 'route-atibaia-4',
        business_id: 'biz-atibaia-5',
        title: 'Pôr do Sol a Dois na Pedra Grande',
        description: 'Brinde com vista panorâmica de tirar o fôlego.',
        sort_order: 2,
      },
    ]
  },
  {
    id: 'route-atibaia-5',
    city_id: 'city-atibaia',
    name: 'Rota dos Sabores, Morango & Empórios (DEMO)',
    slug: 'rota-sabores-morango-emporios-demo',
    description: 'Circuito gastronômico rural para provar doces típicos, morangos premiados, cachaças e pratos coloniais.',
    duration: '1 dia (09h30 às 16h)',
    profile: 'Gastronomia / Compras',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-at-11',
        route_id: 'route-atibaia-5',
        business_id: 'biz-atibaia-8',
        title: 'Compras de Morangos e Geleias no Empório',
        description: 'Degustação e compra de produtos da agricultura familiar.',
        sort_order: 1,
      },
      {
        id: 'ri-at-12',
        route_id: 'route-atibaia-5',
        business_id: 'biz-atibaia-2',
        title: 'Almoço Gastronômico com Morango',
        description: 'Pratos doces e salgados harmonizados com morango de Atibaia.',
        sort_order: 2,
      },
    ]
  },
];

export const ATIBAIA_EVENTS: EventItem[] = [
  {
    id: 'evt-atibaia-1',
    city_id: 'city-atibaia',
    name: '43ª Festa das Flores e do Morango de Atibaia (DEMO)',
    description: 'O maior evento da colônia japonesa e produtores rurais de Atibaia. Pavilhão de exposição de flores, estufas com morangos gigantes, shows folclóricos tradicionais e praça gastronômica oriental e caipira.',
    event_date: '2026-09-04',
    event_time: '09:00 - 18:00',
    location: 'Parque Municipal Edmundo Zanoni - Atibaia - SP',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://floresemorangos.com.br',
    status: 'published',
  },
  {
    id: 'evt-atibaia-2',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-1',
    name: 'Encontro Nacional de Voo Livre da Pedra Grande (DEMO)',
    description: 'Competição espetacular com dezenas de parapentes e asas-deltas colorindo os céus de Atibaia com acrobacias, voos de cross-country e música ao vivo no pouso.',
    event_date: '2026-07-18',
    event_time: '08:30 - 17:30',
    location: 'Rampa de Voo Livre - Monumento Natural da Pedra Grande',
    image_url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://voolivreatibaia.com.br',
    status: 'published',
  },
  {
    id: 'evt-atibaia-3',
    city_id: 'city-atibaia',
    name: 'Festival Gastronômico de Inverno de Atibaia (DEMO)',
    description: 'Restaurantes, bistrôs e cantinas da cidade apresentam menus exclusivos com fondues, caldos quentes, carnes nobres e sobremesas com morango em clima serrano.',
    event_date: '2026-06-20',
    event_time: '12:00 - 23:00',
    location: 'Circuito Gastronômico de Atibaia',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://turismo.atibaia.sp.gov.br',
    status: 'published',
  },
  {
    id: 'evt-atibaia-4',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-6',
    name: 'Festival de Cervejas Artesanais da Mantiqueira (DEMO)',
    description: 'Mais de 15 microcervejarias da serra reunidas com dezenas de torneiras de chopp artesanal, food trucks gourmets e bandas de rock e blues ao ar livre.',
    event_date: '2026-08-15',
    event_time: '14:00 - 22:00',
    location: 'Cervejaria Mantiqueira - Av. Santana, 880',
    image_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://cervejariamanqueira.com.br',
    status: 'published',
  },
  {
    id: 'evt-atibaia-5',
    city_id: 'city-atibaia',
    business_id: 'biz-atibaia-10',
    name: 'Noite de Choro & Tradições no Casarão Julia Ferraz (DEMO)',
    description: 'Roda de choro e samba tradicional brasileiro nos jardins do casarão histórico de 1776, acompanhada de petiscos coloniais e vinho da serra.',
    event_date: '2026-05-23',
    event_time: '19:00 - 22:30',
    location: 'Casarão Julia Ferraz - Centro Histórico',
    image_url: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://casaraojuliaferraz.org.br',
    status: 'published',
  },
];
