import { City, Category, Business, Experience, Route, EventItem } from '@/types';

export const DEMO_CITY: City = {
  id: 'city-sao-roque',
  name: 'São Roque',
  slug: 'sao-roque',
  state: 'SP',
  country: 'Brasil',
  description: 'A Estância Turística de São Roque é famosa pelo Roteiro do Vinho, gastronomia inspirada na imigração portuguesa e italiana, clima acolhedor de serra e belezas naturais.',
  image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',
  is_active: true,
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-vinicolas',
    name: 'Vinícolas & Adegas',
    slug: 'vinicolas-adegas',
    description: 'Conheça parreirais, degustações guiadas e caves históricas no famoso Roteiro do Vinho.',
    icon: 'Wine',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-restaurantes',
    name: 'Restaurantes',
    slug: 'restaurantes',
    description: 'Gastronomia caipira, portuguesa, italiana e contemporânea com vista para a natureza.',
    icon: 'Utensils',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-hospedagem',
    name: 'Hospedagem',
    slug: 'hospedagem',
    description: 'Hotéis fazenda, pousadas charmosas e chalés aconchegantes na montanha.',
    icon: 'Hotel',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-passeios',
    name: 'Passeios & Agências',
    slug: 'passeios-agencias',
    description: 'Trens turísticos, passeios a cavalo, quadriciclo e transportes para vinícolas.',
    icon: 'Bus',
    image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-guias',
    name: 'Guias Turísticos',
    slug: 'guias-turisticos',
    description: 'Profissionais credenciados para acompanhar grupos e famílias nos atrativos locais.',
    icon: 'Compass',
    image_url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-natureza',
    name: 'Natureza & Trilhas',
    slug: 'natureza-trilhas',
    description: 'Mirantes de tirar o fôlego, parques ecológicos e matas preservadas.',
    icon: 'Trees',
    image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-cultura',
    name: 'Cultura & História',
    slug: 'cultura-historia',
    description: 'Patrimônio histórico do século XVII, capelas centenárias e centros culturais.',
    icon: 'Landmark',
    image_url: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-compras',
    name: 'Compras & Doces',
    slug: 'compras-doces',
    description: 'Empórios rurais, alcachofras frescas, queijos artesanais, chocolates e lembranças.',
    icon: 'ShoppingBag',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
];

export const DEMO_BUSINESSES: Business[] = [
  {
    id: 'biz-1',
    city_id: 'city-sao-roque',
    category_id: 'cat-vinicolas',
    name: 'Vinícola Quinta do Olivardo (DEMO)',
    slug: 'vinicola-quinta-do-olivardo-demo',
    description: 'Uma imersão na cultura açoriana e portuguesa em pleno Roteiro do Vinho. Parreirais extensos, produção de vinho dos mortos, pastel de bacalhau e bolinho de chuva servidos em ambiente rústico envolto por serras.',
    address: 'Estrada do Vinho, km 4 - Sorocamirim, São Roque - SP',
    phone: '(11) 4711-1100',
    whatsapp: '5511970881000',
    instagram: 'quintadoolivardo',
    website: 'https://quintadoolivardo.com.br',
    latitude: -23.5385,
    longitude: -47.1611,
    price_min: 75,
    price_max: 220,
    opening_hours: 'Segunda a Domingo, das 09h30 às 17h30',
    main_image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.9,
    review_count: 1420,
    amenities: ['Estacionamento Gratuito', 'Pet Friendly', 'Espaço Kids', 'Acessibilidade', 'Wi-Fi', 'Restaurante Próprio'],
    tags: ['Vinhos', 'Bacalhau', 'Pastel de Belém', 'Roteiro do Vinho', 'Portugal'],
    gallery: [
      { id: 'img-1-1', business_id: 'biz-1', image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80', sort_order: 1 },
      { id: 'img-1-2', business_id: 'biz-1', image_url: 'https://images.unsplash.com/photo-1528823872057-9c018a7a70b3?auto=format&fit=crop&w=800&q=80', sort_order: 2 },
      { id: 'img-1-3', business_id: 'biz-1', image_url: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=800&q=80', sort_order: 3 },
    ]
  },
  {
    id: 'biz-2',
    city_id: 'city-sao-roque',
    category_id: 'cat-vinicolas',
    name: 'Vinícola Góes (DEMO)',
    slug: 'vinicola-goes-demo',
    description: 'Tradição centenária na produção de vinhos de alta qualidade. Tour completo pelas vinhas, adega subterrânea de envelhecimento em barricas de carvalho e restaurante fino especializado na cozinha internacional.',
    address: 'Estrada do Vinho, km 9 - Canguera, São Roque - SP',
    phone: '(11) 4711-3000',
    whatsapp: '5511947113000',
    instagram: 'vinicolagoes',
    website: 'https://vinicolagoes.com.br',
    latitude: -23.5512,
    longitude: -47.1724,
    price_min: 50,
    price_max: 350,
    opening_hours: 'Segunda a Domingo, das 09h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.8,
    review_count: 2150,
    amenities: ['Degustação Guiada', 'Estacionamento com Manobrista', 'Loja Oficial', 'Wi-Fi', 'Restaurante Gourmet'],
    tags: ['Vinhos Finos', 'Degustação', 'Tour Guiado', 'Vindima'],
    gallery: [
      { id: 'img-2-1', business_id: 'biz-2', image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80', sort_order: 1 },
    ]
  },
  {
    id: 'biz-3',
    city_id: 'city-sao-roque',
    category_id: 'cat-restaurantes',
    name: 'Vila Don Patto (DEMO)',
    slug: 'vila-don-patto-demo',
    description: 'Complexo gastronômico deslumbrante com restaurante de culinária portuguesa, cantina italiana, sorveteira, adega completa, heliponto e parquinho para crianças entre bosques verdejantes.',
    address: 'Estrada do Vinho, km 2,5 - Sorocamirim, São Roque - SP',
    phone: '(11) 4711-3001',
    whatsapp: '5511975630000',
    instagram: 'viladonpatto',
    website: 'https://viladonpatto.com.br',
    latitude: -23.5312,
    longitude: -47.1550,
    price_min: 80,
    price_max: 280,
    opening_hours: 'Quarta a Domingo, das 11h às 17h',
    main_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.7,
    review_count: 1890,
    amenities: ['Heliponto', 'Playground', 'Adega', 'Pet Friendly', 'Redário'],
    tags: ['Culinária Portuguesa', 'Massa Artesanal', 'Família', 'Vista Panorâmica'],
  },
  {
    id: 'biz-4',
    city_id: 'city-sao-roque',
    category_id: 'cat-hospedagem',
    name: 'Hotel Villa Michelon (DEMO)',
    slug: 'hotel-villa-michelon-demo',
    description: 'Refúgio de charme e aconchego no coração do Roteiro do Vinho. Quartos acolhedores com lareira, piscinas aquecidas, quadras de tênis, lago de pesca e trilhas ecológicas.',
    address: 'Estrada do Vinho, km 4,5 - Canguera, São Roque - SP',
    phone: '(11) 4711-8000',
    whatsapp: '5511988887777',
    instagram: 'villamichelon',
    website: 'https://villamichelon.com.br',
    latitude: -23.5420,
    longitude: -47.1680,
    price_min: 450,
    price_max: 1200,
    opening_hours: 'Recepção 24 horas',
    main_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    rating: 4.9,
    review_count: 850,
    amenities: ['Piscina Aquecida', 'Café da Manhã Incluso', 'Lareira nos Quartos', 'Wi-Fi de Alta Velocidade', 'Quadra de Tênis'],
    tags: ['Resort', 'Romântico', 'Casal', 'Natureza', 'Piscina'],
  },
  {
    id: 'biz-5',
    city_id: 'city-sao-roque',
    category_id: 'cat-hospedagem',
    name: 'Pousada Chácara da Roseira (DEMO)',
    slug: 'pousada-roseira-demo',
    description: 'Pousada bucólica cercada por jardins floridos e mata atlântica. Chalés privativos com hidromassagem, rede na varanda e café da manhã servido na mesa com quitutes caseiros.',
    address: 'Estrada dos Venâncios, 800 - Sorocamirim, São Roque - SP',
    phone: '(11) 4711-5432',
    whatsapp: '5511999887766',
    instagram: 'pousadachacararoseira',
    website: 'https://pousadaroseira.com.br',
    latitude: -23.5290,
    longitude: -47.1490,
    price_min: 320,
    price_max: 750,
    opening_hours: 'Recepção das 08h às 22h',
    main_image_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: false,
    is_premium: false,
    rating: 4.8,
    review_count: 310,
    amenities: ['Hidromassagem', 'Café da Manhã', 'Estacionamento Gratuito', 'Chalés Privativos'],
    tags: ['Pousada', 'Chalé', 'Casal', 'Aconchegante'],
  },
  {
    id: 'biz-6',
    city_id: 'city-sao-roque',
    category_id: 'cat-restaurantes',
    name: 'Cantina Italiana Bella Italia (DEMO)',
    slug: 'cantina-bella-italia-demo',
    description: 'Tradição em massas artesanais recheadas, polenta frita crocante, antepastos e uma adega seleta com mais de 300 rótulos nacionais e importados.',
    address: 'Av. Antonino Dias Bastos, 450 - Centro, São Roque - SP',
    phone: '(11) 4784-1234',
    whatsapp: '5511977771234',
    instagram: 'bellaitaliasaoroque',
    website: 'https://bellaitaliasaoroque.com.br',
    latitude: -23.5280,
    longitude: -47.1350,
    price_min: 60,
    price_max: 180,
    opening_hours: 'Terça a Domingo, das 12h às 23h',
    main_image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.6,
    review_count: 670,
    amenities: ['Música ao Vivo', 'Adega Climatizada', 'Ar Condicionado', 'Acessibilidade'],
    tags: ['Italiano', 'Massa', 'Vinho', 'Centro'],
  },
  {
    id: 'biz-7',
    city_id: 'city-sao-roque',
    category_id: 'cat-natureza',
    name: 'Parque Ecológico Morro do Saboó (DEMO)',
    slug: 'morro-do-saboo-demo',
    description: 'O ponto mais alto de São Roque com 1.000 metros de altitude. Vista panorâmica inesquecível de 360 graus para várias cidades da região. Trilha de caminhada moderada perfeita para o pôr do sol.',
    address: 'Estrada Municipal do Saboó, s/n - Saboó, São Roque - SP',
    phone: '(11) 4712-4000',
    whatsapp: '5511966665555',
    instagram: 'morrodosaboo.oficial',
    website: 'https://turismo.saoroque.sp.gov.br',
    latitude: -23.5010,
    longitude: -47.0980,
    price_min: 0,
    price_max: 0,
    opening_hours: 'Aberto diariamente das 06h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'free',
    is_featured: true,
    is_premium: false,
    rating: 4.9,
    review_count: 1280,
    amenities: ['Entrada Gratuita', 'Trilha Ecológica', 'Fotografia', 'Estacionamento'],
    tags: ['Trilha', 'Pôr do Sol', 'Vista Panorâmica', 'Gratuito', 'Ecoturismo'],
  },
  {
    id: 'biz-8',
    city_id: 'city-sao-roque',
    category_id: 'cat-passeios',
    name: 'Trem Turístico das Vinhas (DEMO)',
    slug: 'trem-turistico-das-vinhas-demo',
    description: 'Passeio nostálgico a bordo de maria-fumaça histórica ligando o centro de São Roque à região das vinícolas com apresentações musicais e degustação a bordo.',
    address: 'Estação Ferroviária - Praça da Estação, São Roque - SP',
    phone: '(11) 4784-9000',
    whatsapp: '5511944443333',
    instagram: 'tremdasvinhas',
    website: 'https://tremdasvinhas.com.br',
    latitude: -23.5300,
    longitude: -47.1320,
    price_min: 65,
    price_max: 120,
    opening_hours: 'Sábados, Domingos e Feriados com partidas às 10h e 14h',
    main_image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    rating: 4.8,
    review_count: 540,
    amenities: ['Guia a Bordo', 'Degustação Grátis', 'Acessível', 'Ar Condicionado em vagão VIP'],
    tags: ['Maria Fumaça', 'Passeio de Trem', 'Família', 'História'],
  },
  {
    id: 'biz-9',
    city_id: 'city-sao-roque',
    category_id: 'cat-compras',
    name: 'Empório & Chocolateiro Cacau da Serra (DEMO)',
    slug: 'emporio-cacau-da-serra-demo',
    description: 'Chocolates artesanais recheados com licor de vinho, compotas caseiras de alcachofra, queijos premiados da Mantiqueira e salames artesanais curados.',
    address: 'Estrada do Vinho, km 1,5 - São Roque - SP',
    phone: '(11) 4711-2222',
    whatsapp: '5511933332222',
    instagram: 'cacaudaserra',
    website: 'https://cacaudaserra.com.br',
    latitude: -23.5350,
    longitude: -47.1480,
    price_min: 15,
    price_max: 150,
    opening_hours: 'Diariamente das 09h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    rating: 4.7,
    review_count: 420,
    amenities: ['Degustação de Chocolates', 'Cafeteria Própria', 'Embalagens de Presente'],
    tags: ['Chocolate', 'Queijos', 'Alcachofra', 'Souvenirs'],
  },
  {
    id: 'biz-10',
    city_id: 'city-sao-roque',
    category_id: 'cat-cultura',
    name: 'Sítio Santo Antônio - Patrimônio Histórico (DEMO)',
    slug: 'sitio-santo-antonio-demo',
    description: 'Construção bandeirante tombada do século XVII (1681), onde viveu o Barão de Piratininga. Casa de taipas e capela histórica preservadas pelo IPHAN.',
    address: 'Estrada das Moinho, s/n - São Roque - SP',
    phone: '(11) 4712-4001',
    whatsapp: '5511922221111',
    instagram: 'patrimoniosaoroque',
    website: 'https://turismo.saoroque.sp.gov.br',
    latitude: -23.5180,
    longitude: -47.1200,
    price_min: 0,
    price_max: 15,
    opening_hours: 'Terça a Domingo das 09h às 16h30',
    main_image_url: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    rating: 4.6,
    review_count: 380,
    amenities: ['Visita Guiada', 'Acessibilidade Parcial', 'Estacionamento'],
    tags: ['História', 'Bandeirantes', 'Patrimônio', 'Cultura'],
  },
];

export const DEMO_EXPERIENCES: Experience[] = [
  {
    id: 'exp-1',
    city_id: 'city-sao-roque',
    business_id: 'biz-2',
    category_id: 'cat-vinicolas',
    name: 'Degustação Harmonizada Premium na Cave (DEMO)',
    slug: 'degustacao-harmonizada-premium-demo',
    description: 'Sommelier exclusivo guia você pela prova de 5 rótulos de vinhos de safra especial harmonizados com queijos finos, antepastos e pães artesanais dentro da cave subterrânea.',
    price: 130,
    duration: '1h 30min',
    main_image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'exp-2',
    city_id: 'city-sao-roque',
    business_id: 'biz-1',
    category_id: 'cat-vinicolas',
    name: 'Pisa da Uva & Almoço Açoriano (DEMO)',
    slug: 'pisa-da-uva-almoco-acoriano-demo',
    description: 'Reviva a tradição da colheita manual das uvas e a pisa em dornas de madeira ao som de folclore português, seguido de almoço com bacalhau no forno de lenha.',
    price: 210,
    duration: '3h',
    main_image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'exp-3',
    city_id: 'city-sao-roque',
    business_id: 'biz-4',
    category_id: 'cat-hospedagem',
    name: 'Picnic nos Vinhedos ao Pôr do Sol (DEMO)',
    slug: 'picnic-nos-vinhedos-demo',
    description: 'Cesta completa de piquenique com espumante gelado, tábua de frios selecionados, frutas frescas, geleias rurais e toalha xadrez para relaxar no parreiral.',
    price: 180,
    duration: '2h',
    main_image_url: 'https://images.unsplash.com/photo-1528823872057-9c018a7a70b3?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'exp-4',
    city_id: 'city-sao-roque',
    business_id: 'biz-7',
    category_id: 'cat-natureza',
    name: 'Trilha Sunset no Morro do Saboó (DEMO)',
    slug: 'trilha-sunset-saboo-demo',
    description: 'Caminhada guiada rumo ao cume do morro mais alto da região para apreciar o pôr do sol espetacular com brinde de vinho artesanal no topo.',
    price: 45,
    duration: '2h 30min',
    main_image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'exp-5',
    city_id: 'city-sao-roque',
    business_id: 'biz-3',
    category_id: 'cat-restaurantes',
    name: 'Oficina de Pastel de Belém & Doces Portugueses (DEMO)',
    slug: 'oficina-pastel-de-belem-demo',
    description: 'Aprenda os segredos da massa folhada perfeita e do recheio cremoso do legítimo Pastel de Belém com chef confeiteiro nativo.',
    price: 95,
    duration: '1h 45min',
    main_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: false,
  },
];

export const DEMO_ROUTES: Route[] = [
  {
    id: 'route-1',
    city_id: 'city-sao-roque',
    name: 'Roteiro Clássico do Vinho (DEMO)',
    slug: 'roteiro-classico-do-vinho-demo',
    description: 'A experiência definitiva em São Roque. Um dia inteiro visitando vinícolas históricas, provando vinhos premiados e desfrutando de almoço típico português.',
    duration: '1 dia (09h às 17h)',
    profile: 'Casal / Gastronomia / Vinhos',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-1',
        route_id: 'route-1',
        business_id: 'biz-2',
        title: 'Manhã na Vinícola Góes',
        description: 'Comece seu dia com um passeio guiado entre as vinhas e degustação na cave subterrânea.',
        sort_order: 1,
      },
      {
        id: 'ri-2',
        route_id: 'route-1',
        business_id: 'biz-1',
        title: 'Almoço na Quinta do Olivardo',
        description: 'Delicie-se com bacalhau à lagareiro no forno a lenha e bolinhos de bacalhau crocantes.',
        sort_order: 2,
      },
      {
        id: 'ri-3',
        route_id: 'route-1',
        business_id: 'biz-9',
        title: 'Tarde no Empório Cacau da Serra',
        description: 'Compre queijos artesanais, geleias de alcachofra e chocolates de lembrança.',
        sort_order: 3,
      },
    ]
  },
  {
    id: 'route-2',
    city_id: 'city-sao-roque',
    name: 'São Roque em Família (DEMO)',
    slug: 'sao-roque-em-familia-demo',
    description: 'Roteiro divertido e leve planejado para encantar crianças e adultos, incluindo passeio de trem, parquinhos e natureza.',
    duration: '1 dia (10h às 16h30)',
    profile: 'Famílias / Crianças',
    image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-4',
        route_id: 'route-2',
        business_id: 'biz-8',
        title: 'Passeio na Maria Fumaça',
        description: 'Viagem de trem nostálgica com atrações interativas para os pequenos.',
        sort_order: 1,
      },
      {
        id: 'ri-5',
        route_id: 'route-2',
        business_id: 'biz-3',
        title: 'Almoço & Lazer no Vila Don Patto',
        description: 'Espaço com playground amplo, sorveteira artesanal e brinquedoteca.',
        sort_order: 2,
      },
    ]
  },
  {
    id: 'route-3',
    city_id: 'city-sao-roque',
    name: 'Natureza & Ecoturismo (DEMO)',
    slug: 'natureza-ecoturismo-demo',
    description: 'Para amantes de ar puro, vistas panorâmicas, caminhadas refrescantes e patrimônio cultural preservado.',
    duration: '1 dia (08h às 18h)',
    profile: 'Aventura / Natureza',
    image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-6',
        route_id: 'route-3',
        business_id: 'biz-10',
        title: 'Visita ao Sítio Santo Antônio',
        description: 'Patrimônio colonial do século XVII envolvido por mata preservada.',
        sort_order: 1,
      },
      {
        id: 'ri-7',
        route_id: 'route-3',
        business_id: 'biz-7',
        title: 'Subida ao Morro do Saboó',
        description: 'Caminhada panorâmica até o topo para contemplar a serra e o pôr do sol.',
        sort_order: 2,
      },
    ]
  },
  {
    id: 'route-4',
    city_id: 'city-sao-roque',
    name: 'Fim de Semana Romântico (DEMO)',
    slug: 'fim-de-semana-romantico-demo',
    description: 'Dois dias inesquecíveis a dois com hospedagem aconchegante, jantares à luz de velas e degustações exclusivas.',
    duration: '2 dias (Sábado e Domingo)',
    profile: 'Casais / Romance',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    status: 'published',
    items: [
      {
        id: 'ri-8',
        route_id: 'route-4',
        business_id: 'biz-4',
        title: 'Check-in no Hotel Villa Michelon',
        description: 'Relaxar no chalé com hidromassagem e lareira acessa.',
        sort_order: 1,
      },
      {
        id: 'ri-9',
        route_id: 'route-4',
        business_id: 'biz-6',
        title: 'Jantar na Cantina Bella Italia',
        description: 'Massa artesanal harmonizada com vinho tinto reserva.',
        sort_order: 2,
      },
    ]
  },
];

export const DEMO_EVENTS: EventItem[] = [
  {
    id: 'evt-1',
    city_id: 'city-sao-roque',
    business_id: 'biz-2',
    name: 'Festa da Vindima de São Roque 2026 (DEMO)',
    description: 'Celebração tradicional da colheita das uvas com música ao vivo, pisa das uvas em dornas comunitárias, feira artesanal e alta gastronomia.',
    event_date: '2026-02-20',
    event_time: '10:00 - 18:00',
    location: 'Vinícola Góes - Estrada do Vinho, km 9',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://vinicolagoes.com.br',
    status: 'published',
  },
  {
    id: 'evt-2',
    city_id: 'city-sao-roque',
    business_id: 'biz-1',
    name: 'Noite de Fados Portugueses & Vinho dos Mortos (DEMO)',
    description: 'Apresentação emocionante de fadistas vindos de Lisboa, acompanhados de guitarra portuguesa e jantar especial com bacalhau.',
    event_date: '2026-03-14',
    event_time: '19:30 - 23:00',
    location: 'Quinta do Olivardo - Estrada do Vinho, km 4',
    image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://quintadoolivardo.com.br',
    status: 'published',
  },
  {
    id: 'evt-3',
    city_id: 'city-sao-roque',
    name: 'Festival Gastronômico da Alcachofra (DEMO)',
    description: 'Chefs locais apresentam receitas criativas preparadas com a famosa alcachofra cultivada no microclima único de São Roque.',
    event_date: '2026-10-05',
    event_time: '11:00 - 22:00',
    location: 'Recinto de Festas Vasco Barioni - Centro',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://turismo.saoroque.sp.gov.br',
    status: 'published',
  },
  {
    id: 'evt-4',
    city_id: 'city-sao-roque',
    business_id: 'biz-3',
    name: 'Sunset Sunset Jazz & Wine na Vila (DEMO)',
    description: 'Música instrumental ao vivo no gramado com os melhores rótulos de vinhos locais e tábuas de frios artesanais ao pôr do sol.',
    event_date: '2026-04-18',
    event_time: '16:00 - 20:00',
    location: 'Vila Don Patto - Estrada do Vinho, km 2,5',
    image_url: 'https://images.unsplash.com/photo-1528823872057-9c018a7a70b3?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://viladonpatto.com.br',
    status: 'published',
  },
  {
    id: 'evt-5',
    city_id: 'city-sao-roque',
    name: 'Caminhada Noturna nas Estrelas - Saboó (DEMO)',
    description: 'Subida noturna com astrofotógrafos para observação do céu estrelado e constelações no cume do morro.',
    event_date: '2026-05-09',
    event_time: '20:00 - 23:30',
    location: 'Morro do Saboó',
    image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    external_url: 'https://turismo.saoroque.sp.gov.br',
    status: 'published',
  },
];
