import { City, Category, Business, Experience, Route, EventItem } from '@/types';

export const DEMO_CITY: City = {
  id: 'city-sao-roque',
  name: 'São Roque',
  slug: 'sao-roque',
  state: 'SP',
  country: 'Brasil',
  badge: 'Estância Turística de São Roque - SP',
  subtitle: 'Vinhos, gastronomia e experiências',
  description: 'A Estância Turística de São Roque é a capital paulista do enoturismo, famosa pelo histórico Roteiro do Vinho, culinária inspirada na imigração portuguesa e italiana, clima acolhedor de serra e belezas naturais.',
  image_url: '/images/hero-sao-roque.webp',
  hero_image: '/images/hero-sao-roque.webp',
  tags: ['Vinhos', 'Gastronomia', 'Natureza', 'Experiências'],
  is_active: true,
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-vinicolas',
    city_id: 'city-sao-roque',
    name: 'Vinícolas & Adegas',
    slug: 'vinicolas-adegas',
    description: 'Conheça parreirais centenários, degustações guiadas e caves históricas no famoso Roteiro do Vinho.',
    icon: 'Wine',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-restaurantes',
    city_id: 'city-sao-roque',
    name: 'Restaurantes & Gastronomia',
    slug: 'restaurantes',
    description: 'Gastronomia portuguesa, cantinas italianas, pratos com alcachofra e carnes nobres na brasa.',
    icon: 'Utensils',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-hospedagem',
    city_id: 'city-sao-roque',
    name: 'Hospedagem & Pousadas',
    slug: 'hospedagem',
    description: 'Resorts de luxo, pousadas charmosas com lareira e chalés românticos nas montanhas.',
    icon: 'Hotel',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-passeios',
    city_id: 'city-sao-roque',
    name: 'Passeios & Lazer',
    slug: 'passeios-agencias',
    description: 'Ski Mountain Park, trilhas ecológicas, mirantes e passeios panorâmicos.',
    icon: 'Bus',
    image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-compras',
    city_id: 'city-sao-roque',
    name: 'Compras & Empórios',
    slug: 'compras-doces',
    description: 'Empórios rurais, alcachofras frescas, queijos artesanais, licores e chocolates finos.',
    icon: 'ShoppingBag',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-cultura',
    city_id: 'city-sao-roque',
    name: 'Cultura & Patrimônio',
    slug: 'cultura-historia',
    description: 'Capelas do século XVII, Sítio Santo Antônio e história dos bandeirantes.',
    icon: 'Landmark',
    image_url: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
];

export const DEMO_BUSINESSES: Business[] = [
  {
    id: 'biz-sr-1',
    city_id: 'city-sao-roque',
    category_id: 'cat-vinicolas',
    name: 'Vinícola Góes',
    slug: 'vinicola-goes',
    description: 'A mais tradicional e premiada vinícola de São Roque. Oferece passeios guiados pelos vinhedos e caves subterrâneas, degustações orientadas por enólogos, restaurante com vista panorâmica e loja completa de vinhos finos e sucos de uva integrais.',
    address: 'Estrada do Vinho, km 9 - Canguera, São Roque - SP',
    phone: '(11) 4711-3500',
    whatsapp: '5511997873500',
    instagram: 'vinicolagoes',
    website: 'https://vinicolagoes.com.br',
    latitude: -23.5789,
    longitude: -47.1685,
    price_min: 45,
    price_max: 220,
    opening_hours: 'Segunda a Domingo, das 09h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    images: [
      { id: 'img-sr-1-1', business_id: 'biz-sr-1', image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80', sort_order: 1 },
      { id: 'img-sr-1-2', business_id: 'biz-sr-1', image_url: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=1000&q=80', sort_order: 2 },
    ],
  },
  {
    id: 'biz-sr-2',
    city_id: 'city-sao-roque',
    category_id: 'cat-vinicolas',
    name: 'Quinta do Olivardo',
    slug: 'quinta-do-olivardo',
    description: 'Uma imersão encantadora na cultura açoriana e portuguesa em pleno Roteiro do Vinho. Famosa pelos pastéis de nata fresquinhos servidos ao toque do sino, o tradicional Vinho dos Mortos, bacalhau na brasa, tirolesa infantil e parreirais em socalcos.',
    address: 'Estrada do Vinho, km 4 - Sorocamirim, São Roque - SP',
    phone: '(11) 4711-1100',
    whatsapp: '5511970881000',
    instagram: 'quintadoolivardo',
    website: 'https://quintadoolivardo.com.br',
    latitude: -23.5512,
    longitude: -47.1523,
    price_min: 60,
    price_max: 250,
    opening_hours: 'Segunda a Domingo, das 09h30 às 17h30',
    main_image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    images: [
      { id: 'img-sr-2-1', business_id: 'biz-sr-2', image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80', sort_order: 1 },
      { id: 'img-sr-2-2', business_id: 'biz-sr-2', image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80', sort_order: 2 },
    ],
  },
  {
    id: 'biz-sr-3',
    city_id: 'city-sao-roque',
    category_id: 'cat-restaurantes',
    name: 'Cantina Tia Lina',
    slug: 'cantina-tia-lina',
    description: 'Referência em culinária italiana artesanal no Roteiro do Vinho. Famosa pelo clássico Rondelli quatro queijos com alcachofra cultivada na cidade, polenta cremosa com ragu de linguiça e carta de vinhos regionais.',
    address: 'Estrada do Vinho, km 10,4 - Canguera, São Roque - SP',
    phone: '(11) 4711-2018',
    whatsapp: '5511999882018',
    instagram: 'cantinatialina',
    website: 'https://cantinatialina.com.br',
    latitude: -23.5854,
    longitude: -47.1723,
    price_min: 75,
    price_max: 180,
    opening_hours: 'Sexta a Domingo e Feriados, das 11h30 às 17h',
    main_image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    images: [
      { id: 'img-sr-3-1', business_id: 'biz-sr-3', image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80', sort_order: 1 },
    ],
  },
  {
    id: 'biz-sr-4',
    city_id: 'city-sao-roque',
    category_id: 'cat-restaurantes',
    name: 'Vila Don Patto',
    slug: 'vila-don-patto',
    description: 'Amplo complexo enogastronômico e turístico integrado à Mata Atlântica. Dispõe de restaurante português de alta gastronomia, restaurante italiano, boulangerie artesanal, empório gourmet, cafeteria e amplo espaço kids.',
    address: 'Estrada do Vinho, km 2,5 - Sorocamirim, São Roque - SP',
    phone: '(11) 4711-3001',
    whatsapp: '5511975632001',
    instagram: 'viladonpatto',
    website: 'https://viladonpatto.com.br',
    latitude: -23.5412,
    longitude: -47.1421,
    price_min: 80,
    price_max: 280,
    opening_hours: 'Segunda a Domingo, das 09h às 17h30',
    main_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    images: [
      { id: 'img-sr-4-1', business_id: 'biz-sr-4', image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80', sort_order: 1 },
    ],
  },
  {
    id: 'biz-sr-5',
    city_id: 'city-sao-roque',
    category_id: 'cat-vinicolas',
    name: 'Vinícola Canguera',
    slug: 'vinicola-canguera',
    description: 'Fundada no início dos anos 1950, a Canguera abriga o Museu do Vinho de São Roque, tonéis gigantes de carvalho centenários e degustação orientada de licores artesanais, frisantes e vinhos de mesa e finos.',
    address: 'Estrada do Vinho, km 8 - Canguera, São Roque - SP',
    phone: '(11) 4711-1404',
    whatsapp: '5511998551404',
    instagram: 'vinicolacanguera',
    website: 'https://vinicolacanguera.com.br',
    latitude: -23.5712,
    longitude: -47.1643,
    price_min: 30,
    price_max: 150,
    opening_hours: 'Segunda a Domingo, das 09h às 17h30',
    main_image_url: 'https://images.unsplash.com/photo-1528823872057-9c018a7a7553?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
  },
  {
    id: 'biz-sr-6',
    city_id: 'city-sao-roque',
    category_id: 'cat-hospedagem',
    name: 'Hotel Villa Rossa',
    slug: 'hotel-villa-rossa',
    description: 'Resort de luxo encravado em 350 mil m² de Mata Atlântica preservada. Possui spa privativo com tratamentos corporais, piscinas climatizadas e aquecidas, gastronomia internacional com buffet temático e suítes com lareira e varanda privativa.',
    address: 'Rua Cora Coralina, 350 - Vila Darcy Penteado, São Roque - SP',
    phone: '(11) 4713-5560',
    whatsapp: '5511964555560',
    instagram: 'hotelvillarossa',
    website: 'https://villarossa.com.br',
    latitude: -23.5187,
    longitude: -47.1089,
    price_min: 850,
    price_max: 2200,
    opening_hours: 'Recepção 24 horas',
    main_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
  },
  {
    id: 'biz-sr-7',
    city_id: 'city-sao-roque',
    category_id: 'cat-hospedagem',
    name: 'Pousada Acalanto da Serra',
    slug: 'pousada-acalanto-da-serra',
    description: 'Refúgio romântico e aconchegante para casais, localizado no topo das colinas de São Roque. Oferece chalés rústicos e elegantes equipados com banheira de hidromassagem dupla, lareira a lenha e café da manhã colonial com pães e geleias artesanais.',
    address: 'Estrada da Serrinha, 800 - Ibaté, São Roque - SP',
    phone: '(11) 4712-4422',
    whatsapp: '5511973344422',
    instagram: 'pousadaacalantodaserra',
    website: 'https://pousadaacalanto.com.br',
    latitude: -23.5387,
    longitude: -47.1299,
    price_min: 420,
    price_max: 980,
    opening_hours: 'Check-in a partir das 14h / Check-out até às 12h',
    main_image_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
  },
  {
    id: 'biz-sr-8',
    city_id: 'city-sao-roque',
    category_id: 'cat-passeios',
    name: 'Ski Mountain Park',
    slug: 'ski-mountain-park',
    description: 'Parque temático de montanha situado a mais de 1.200 metros de altitude com vista espetacular de toda a região de São Roque. Oferece pistas artificiais de esqui e snowboard, tobogã gigante, arvorismo, tirolesa, arco e flecha e restaurante de montanha.',
    address: 'Estrada da Serrinha, s/n - Cambará, São Roque - SP',
    phone: '(11) 4712-3299',
    whatsapp: '5511996553299',
    instagram: 'skipark_oficial',
    website: 'https://skipark.com.br',
    latitude: -23.5298,
    longitude: -47.1245,
    price_min: 50,
    price_max: 160,
    opening_hours: 'Sexta a Domingo e Feriados, das 09h às 17h',
    main_image_url: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
  },
  {
    id: 'biz-sr-9',
    city_id: 'city-sao-roque',
    category_id: 'cat-restaurantes',
    name: 'Restaurante Cascudo',
    slug: 'restaurante-cascudo',
    description: 'Especializado em carnes nobres grelhadas na brasa e gastronomia caipira refinada. Ambiente aconchegante rodeado de jardins floridos no Roteiro do Vinho, com chope artesanal bem gelado e sobremesas caseiras da fazenda.',
    address: 'Estrada do Vinho, km 6 - Sorocamirim, São Roque - SP',
    phone: '(11) 4711-2550',
    whatsapp: '5511998332550',
    instagram: 'restaurantecascudo',
    website: 'https://restaurantecascudo.com.br',
    latitude: -23.5623,
    longitude: -47.1587,
    price_min: 70,
    price_max: 190,
    opening_hours: 'Quinta a Domingo, das 11h30 às 17h',
    main_image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
  },
  {
    id: 'biz-sr-10',
    city_id: 'city-sao-roque',
    category_id: 'cat-compras',
    name: 'Empório & Alcachofras São Roque',
    slug: 'emporio-alcachofras-sao-roque',
    description: 'O melhor ponto de parada para adquirir alcachofras frescas cultivadas na região, fundos de alcachofra em conserva, patês artesanais, queijos da Canastra, vinhos artesanais e o famoso licor de alcachofra.',
    address: 'Estrada do Vinho, km 1 - Sorocamirim, São Roque - SP',
    phone: '(11) 4711-1880',
    whatsapp: '5511971221880',
    instagram: 'alcachofrassaoroque',
    website: 'https://alcachofrassaoroque.com.br',
    latitude: -23.5356,
    longitude: -47.1388,
    price_min: 25,
    price_max: 120,
    opening_hours: 'Todos os dias, das 09h às 18h',
    main_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
  },
];

export const DEMO_EXPERIENCES: Experience[] = [
  {
    id: 'exp-sr-1',
    city_id: 'city-sao-roque',
    business_id: 'biz-sr-1',
    category_id: 'cat-vinicolas',
    name: 'Tour das Caves & Degustação Orientada de Vinhos Finos',
    slug: 'tour-das-caves-degustacao-orientada-vinicola-goes',
    description: 'Acompanhado por um enólogo da Vinícola Góes, conheça a história do vinho em São Roque, caminhe pelos parreirais e pelas caves subterrâneas de envelhecimento em barricas de carvalho, finalizando com a degustação comentada de 5 rótulos premiados acompanhados de tábua de queijos.',
    price: 95,
    duration: '1h45',
    main_image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    included: [
      'Visita guiada às caves subterrâneas de carvalho',
      'Degustação de 5 vinhos finos premiados',
      'Taça de cristal personalizada de brinde',
      'Tábua individual de queijos e frios artesanais',
    ],
  },
  {
    id: 'exp-sr-2',
    city_id: 'city-sao-roque',
    business_id: 'biz-sr-2',
    category_id: 'cat-vinicolas',
    name: 'Piquenique Colonial nos Vinhedos Açorianos',
    slug: 'piquenique-colonial-vinhedos-quinta-do-olivardo',
    description: 'Uma tarde inesquecível em meio aos parreirais da Quinta do Olivardo. Uma toalha xadrez estendida na grama com cesta colonial recheada de pães caseiros, pastéis de nata quentinhos, bolinhos de bacalhau, queijo curado, frutas frescas e uma garrafa de vinho ou espumante da casa.',
    price: 180,
    duration: '2h30',
    main_image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    included: [
      'Cesta completa colonial para 2 pessoas',
      'Garrafa de vinho ou espumante Quinta do Olivardo',
      'Porção de pastéis de nata artesanais',
      'Área reservada e exclusiva nos vinhedos',
    ],
  },
  {
    id: 'exp-sr-3',
    city_id: 'city-sao-roque',
    business_id: 'biz-sr-8',
    category_id: 'cat-passeios',
    name: 'Passaporte Aventura & Pistas de Neve no Ski Park',
    slug: 'passaporte-aventura-ski-mountain-park',
    description: 'Um dia repleto de adrenalina e diversão para toda a família nas montanhas de São Roque. Inclui acesso às pistas de esqui e snowboard com instrutor, descidas no tobogã gigante de 350 metros, circuito de arvorismo e tirolesa com vista panorâmica.',
    price: 130,
    duration: '4 horas',
    main_image_url: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    included: [
      '30 minutos de pista de esqui/snowboard com equipamentos',
      '3 descidas no tobogã panorâmico',
      'Circuito de tirolesa e arvorismo',
      'Acesso ao mirante das montanhas',
    ],
  },
];

export const DEMO_ROUTES: Route[] = [
  {
    id: 'route-sr-1',
    city_id: 'city-sao-roque',
    name: 'Roteiro Clássico do Vinho e Gastronomia Portuguesa',
    slug: 'roteiro-classico-do-vinho-sao-roque',
    description: 'O itinerário perfeito de 1 dia para conhecer os pontos mais emblemáticos e deliciosos da Estrada do Vinho. Parreirais, caves históricas, almoço português autêntico e pôr do sol com pastéis de nata.',
    duration: '1 Dia Completo',
    profile: 'Casal & Família',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'ri-sr-1-1',
        route_id: 'route-sr-1',
        business_id: 'biz-sr-1',
        title: '09h30 - Chegada e Tour nas Caves da Vinícola Góes',
        description: 'Comece a manhã com um passeio tranquilo pelos vinhedos e uma degustação guiada de vinhos finos nas caves de carvalho.',
        sort_order: 1,
      },
      {
        id: 'ri-sr-1-2',
        route_id: 'route-sr-1',
        business_id: 'biz-sr-4',
        title: '12h30 - Almoço Enogastronômico na Vila Don Patto',
        description: 'Saboreie o clássico bacalhau na brasa ou massas frescas em meio à natureza com vista panorâmica da Mata Atlântica.',
        sort_order: 2,
      },
      {
        id: 'ri-sr-1-3',
        route_id: 'route-sr-1',
        business_id: 'biz-sr-5',
        title: '15h00 - Museu do Vinho na Vinícola Canguera',
        description: 'Conheça o acervo histórico do vinho paulista, tonéis gigantes de madeira e experimente licores artesanais.',
        sort_order: 3,
      },
      {
        id: 'ri-sr-1-4',
        route_id: 'route-sr-1',
        business_id: 'biz-sr-2',
        title: '16h30 - Tarde Açoriana na Quinta do Olivardo',
        description: 'Assista à saída dos pastéis de nata ao toque do sino e aprecie o pôr do sol sobre os parreirais com café fresquinho.',
        sort_order: 4,
      },
    ],
  },
  {
    id: 'route-sr-2',
    city_id: 'city-sao-roque',
    name: 'Fim de Semana Romântico nas Montanhas de São Roque',
    slug: 'fim-de-semana-romantico-sao-roque',
    description: 'Dois dias de descanso, romantismo e experiências exclusivas com hospedagem em chalé com hidromassagem, jantares à luz de velas e degustações selecionadas.',
    duration: '2 Dias / 1 Noite',
    profile: 'Romântico / Casais',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'ri-sr-2-1',
        route_id: 'route-sr-2',
        business_id: 'biz-sr-7',
        title: 'Sábado 14h00 - Check-in na Pousada Acalanto da Serra',
        description: 'Instalação no chalé com hidromassagem e lareira, com vista panorâmica para o vale.',
        sort_order: 1,
      },
      {
        id: 'ri-sr-2-2',
        route_id: 'route-sr-2',
        business_id: 'biz-sr-3',
        title: 'Sábado 19h30 - Jantar Italiano na Cantina Tia Lina',
        description: 'Jantar especial com alcachofras gratinadas, massas frescas e vinhos da serra.',
        sort_order: 2,
      },
      {
        id: 'ri-sr-2-3',
        route_id: 'route-sr-2',
        business_id: 'biz-sr-2',
        title: 'Domingo 11h30 - Piquenique nos Vinhedos da Quinta do Olivardo',
        description: 'Cesta colonial de piquenique com espumante e doces portugueses.',
        sort_order: 3,
      },
    ],
  },
];

export const DEMO_EVENTS: EventItem[] = [
  {
    id: 'evt-sr-1',
    city_id: 'city-sao-roque',
    business_id: 'biz-sr-1',
    name: 'Pisa da Uva & Vindima de São Roque 2026',
    title: 'Pisa da Uva & Vindima de São Roque 2026',
    slug: 'pisa-da-uva-vindima-sao-roque-2026',
    description: 'A mais tradicional celebração da colheita da uva. Os visitantes colhem os cachos diretamente nos parreirais e realizam a clássica pisa da uva nas tinas ao som de música típica italiana e portuguesa, seguido de almoço festivo.',
    event_date: '2026-09-18',
    start_date: '2026-09-18',
    end_date: '2026-09-27',
    event_time: '10h00 às 16h00',
    location: 'Vinícola Góes - Estrada do Vinho, km 9, São Roque - SP',
    image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'evt-sr-2',
    city_id: 'city-sao-roque',
    name: 'Festival da Alcachofra e Gastronomia de Inverno',
    title: 'Festival da Alcachofra e Gastronomia de Inverno',
    slug: 'festival-da-alcachofra-sao-roque',
    description: 'Grande festival gastronômico anual que reúne os melhores chefs da região preparando pratos criativos à base de alcachofra fresca, vinhos locais, música ao vivo e feira de artesanato.',
    event_date: '2026-10-09',
    start_date: '2026-10-09',
    end_date: '2026-10-18',
    event_time: '11h00 às 22h00',
    location: 'Recanto da Cascata - Av. Antônio Maria Picena, 34, São Roque - SP',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
];
