import { City, Category, Business, Experience, Route, EventItem } from '@/types';

export const SOCORRO_CITY: City = {
  id: 'city-socorro',
  name: 'Socorro',
  slug: 'socorro',
  state: 'SP',
  country: 'Brasil',
  badge: 'Estância Hidromineral de Socorro - SP',
  subtitle: 'Capital da Aventura, Natureza e Ecoturismo.',
  description: 'Capital nacional do turismo de aventura e referência internacional em ecoturismo acessível no Circuito das Águas Paulista. Famosa pelas corredeiras do Rio do Peixe, mirantes com pôr do sol inesquecível na Pedra Bela Vista, gastronomia caipira no fogão a lenha e polo de confecções e malhas.',
  image_url: '/images/socorro/hero.webp',
  hero_image: '/images/socorro/hero.webp',
  tags: ['Aventura', 'Rafting', 'Natureza', 'Ecoturismo', 'Malhas'],
  is_active: true,
};

export const SOCORRO_CATEGORIES: Category[] = [
  {
    id: 'cat-socorro-aventura',
    city_id: 'city-socorro',
    name: 'Aventura & Rafting',
    slug: 'aventura-rafting',
    description: 'Rafting no Rio do Peixe, tirolesas gigantes, arvorismo, quadriciclos e passeios 4x4.',
    icon: 'Compass',
    image_url: '/images/socorro/aventura.webp',
    is_active: true,
  },
  {
    id: 'cat-socorro-natureza',
    city_id: 'city-socorro',
    name: 'Natureza & Mirantes',
    slug: 'natureza-mirantes',
    description: 'Mirante Pedra Bela Vista, Gruta do Anjo, Mirante do Cristo e cachoeiras cristalinas.',
    icon: 'Mountain',
    image_url: '/images/socorro/hero.webp',
    is_active: true,
  },
  {
    id: 'cat-socorro-pousadas',
    city_id: 'city-socorro',
    name: 'Pousadas & Chalés',
    slug: 'pousadas-chales',
    description: 'Pousadas charmosas na serra, chalés com lareira e hidromassagem com vista para as montanhas.',
    icon: 'Hotel',
    image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-gastronomia',
    city_id: 'city-socorro',
    name: 'Gastronomia Caipira',
    slug: 'gastronomia-caipira',
    description: 'Comida no fogão a lenha, leitoa pururuca, trutas frescas e churrasco de chão.',
    icon: 'Utensils',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-cervejarias',
    city_id: 'city-socorro',
    name: 'Cervejarias Artesanais',
    slug: 'cervejarias-artesanais',
    description: 'Fábricas de cerveja artesanal produzidas com água mineral pura da Mantiqueira e taprooms.',
    icon: 'Beer',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-malhas',
    city_id: 'city-socorro',
    name: 'Compras & Malhas',
    slug: 'compras-malhas',
    description: 'Feira permanente de malhas, moda tricô direto dos fabricantes, couro e artesanato.',
    icon: 'ShoppingBag',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-hoteis-fazenda',
    city_id: 'city-socorro',
    name: 'Hotéis Fazenda',
    slug: 'hoteis-fazenda',
    description: 'Resorts rurais premiados internacionalmente em acessibilidade, lazer e pensão completa.',
    icon: 'Trees',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
];

export const SOCORRO_BUSINESSES: Business[] = [
  {
    id: 'biz-socorro-1',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-aventura',
    name: 'Próxima Aventura Rafting & Ecoturismo',
    slug: 'proxima-aventura-rafting-socorro',
    description: 'Operadora pioneira de esportes aquáticos e turismo de aventura no Rio do Peixe. Especializada em rafting com diferentes níveis de corredeiras (iniciante ao avançado), duck radical, boia cross e tirolesa com instrutores certificados internacionalmente pela IRF e equipamentos de ponta.',
    address: 'Estrada Socorro / Munhoz, km 4,5 - Corredor Turístico do Rio do Peixe, Socorro - SP',
    phone: '(19) 3895-1234',
    whatsapp: '5519998771234',
    instagram: 'proximaaventura_socorro',
    website: 'https://proximaaventura.com.br',
    latitude: -22.5901,
    longitude: -46.5298,
    price_min: 90,
    price_max: 220,
    opening_hours: 'Segunda a Domingo: 08h30 às 18h00',
    main_image_url: '/images/socorro/aventura.webp',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    amenities: ['Vestiários com Ducha Quente', 'Fotos em Alta Resolução Inclusas', 'Equipamento de Segurança Homologado', 'Lanchonete no Local', 'Pet Friendly'],
    tags: ['Aventura', 'Rafting', 'Rio do Peixe', 'Tirolesa', 'Adrenalina'],
    rating: 4.9,
    review_count: 1240,
    images: [
      { id: 'img-soc-1-1', business_id: 'biz-socorro-1', image_url: '/images/socorro/aventura.webp', sort_order: 1 },
    ],
  },
  {
    id: 'biz-socorro-2',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-natureza',
    name: 'Mirante Pedra Bela Vista Bar & Gastronomia',
    slug: 'mirante-pedra-bela-vista-socorro',
    description: 'O mirante mais famoso e cinematográfico de Socorro, localizado a 1.250 metros de altitude com vista panorâmica de 360° para a Serra da Mantiqueira. Cenário perfeito para o pôr do sol, servindo o tradicional Pan de Palo assado na fogueira, chope artesanal e rock acústico ao entardecer.',
    address: 'Estrada Municipal dos Goularts, s/n - Bairro Bela Vista, Socorro - SP',
    phone: '(19) 3895-2000',
    whatsapp: '5519998882000',
    instagram: 'pedrabelavista',
    website: 'https://pedrabelavista.com.br',
    latitude: -22.6102,
    longitude: -46.5403,
    price_min: 40,
    price_max: 130,
    opening_hours: 'Quarta a Domingo: 12h00 às 21h00',
    main_image_url: '/images/socorro/hero.webp',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    amenities: ['Mirante Panorâmico 360°', 'Pan de Palo na Fogueira', 'Chopes Artesanais', 'Música ao Vivo', 'Rapel Panorâmico'],
    tags: ['Mirante', 'Pôr do Sol', 'Pedra Bela Vista', 'Pan de Palo', 'Romântico'],
    rating: 5.0,
    review_count: 2400,
    images: [
      { id: 'img-soc-2-1', business_id: 'biz-socorro-2', image_url: '/images/socorro/hero.webp', sort_order: 1 },
    ],
  },
  {
    id: 'biz-socorro-3',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-natureza',
    name: 'Gruta do Anjo Parque Ecológico',
    slug: 'gruta-do-anjo-parque-ecologico',
    description: 'Antiga mina de minerais desativada nos anos 1990 que foi tomada por nascentes de água mineral cristalina, formando um lago interior esmeralda em galerias de rocha iluminadas. O passeio em pedalinhos entre as paredes rochosas é uma das atrações mais icônicas de Socorro.',
    address: 'Estrada Socorro / Munhoz, km 1 - Bairro dos Leais, Socorro - SP',
    phone: '(19) 3895-3000',
    whatsapp: '5519997773000',
    instagram: 'grutadoanjosocorro',
    website: 'https://grutadoanjo.com.br',
    latitude: -22.5854,
    longitude: -46.5182,
    price_min: 35,
    price_max: 70,
    opening_hours: 'Terça a Domingo: 09h00 às 17h00',
    main_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    amenities: ['Passeio de Pedalinho', 'Lanchonete & Empório', 'Estacionamento Próprio', 'Piscina Natural', 'Acessibilidade'],
    tags: ['Gruta do Anjo', 'Caverna', 'Pedalinho', 'Família', 'Natureza'],
    rating: 4.8,
    review_count: 1180,
  },
  {
    id: 'biz-socorro-4',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-hoteis-fazenda',
    name: 'Hotel Fazenda Campo dos Sonhos',
    slug: 'hotel-fazenda-campo-dos-sonhos',
    description: 'Resort rural premiado pela ONU e pelo World Responsible Tourism Awards como referência mundial em turismo sustentável e 100% acessível. Oferece passeios a cavalo, ordenha na fazenda, quadriciclos, tirolesas acessíveis, piscinas cobertas e aquecidas e pensão completa.',
    address: 'Estrada dos Sonhos, km 6 - Bairro Lavras de Baixo, Socorro - SP',
    phone: '(19) 3895-4000',
    whatsapp: '5519996664000',
    instagram: 'campodossonhos',
    website: 'https://campodossonhos.com.br',
    latitude: -22.5621,
    longitude: -46.4912,
    price_min: 680,
    price_max: 1950,
    opening_hours: 'Recepção 24 horas / Day use com agendamento',
    main_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    amenities: ['100% Acessível', 'Pensão Completa 4 Refeições', 'Piscinas Climatizadas e Aquecidas', 'Passeio a Cavalo & Carroça', 'Pesca Esportiva'],
    tags: ['Hotel Fazenda', 'Acessibilidade', 'Família', 'Pensão Completa', 'Cavalgada'],
    rating: 4.9,
    review_count: 1850,
  },
  {
    id: 'biz-socorro-5',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-aventura',
    name: 'Parque de Aventura Monjolinho',
    slug: 'parque-de-aventura-monjolinho',
    description: 'Grande complexo de lazer e aventura às margens do Rio do Peixe. Possui circuitos de tirolesas que cruzam as corredeiras, arvorismo na copa das árvores, trilhas para cachoeiras, stand up paddle, praia de rio e restaurante caipira com fogão a lenha.',
    address: 'Estrada Socorro / Munhoz, km 6 - Corredor Turístico do Rio do Peixe, Socorro - SP',
    phone: '(19) 3895-5000',
    whatsapp: '5519995555000',
    instagram: 'parquemonjolinho',
    website: 'https://parquemonjolinho.com.br',
    latitude: -22.5934,
    longitude: -46.5312,
    price_min: 25,
    price_max: 180,
    opening_hours: 'Todos os dias das 09h00 às 17h30',
    main_image_url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    amenities: ['Tirolesa do Rio', 'Arvorismo', 'Praia de Rio', 'Restaurante Caipira', 'Pet Friendly'],
    tags: ['Parque de Aventura', 'Tirolesa', 'Rio do Peixe', 'Família', 'Cachoeira'],
    rating: 4.8,
    review_count: 980,
  },
  {
    id: 'biz-socorro-6',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-cervejarias',
    name: 'Cervejaria Quinta do Malte',
    slug: 'cervejaria-quinta-do-malte',
    description: 'Cervejaria artesanal premiada com fábrica própria e taproom em Socorro. Chopes produzidos com água pura mineral das montanhas da Mantiqueira, carta com mais de 8 estilos on tap (IPA, Pilsen, Weiss, Red Ale, Stout), petiscos alemães e souvenirs.',
    address: 'Rodovia Pompeu Conti, 3230 - Bairro Salto, Socorro - SP',
    phone: '(19) 3895-6000',
    whatsapp: '5519994446000',
    instagram: 'quintadomalte',
    website: 'https://quintadomalte.com.br',
    latitude: -22.6045,
    longitude: -46.5123,
    price_min: 35,
    price_max: 120,
    opening_hours: 'Quarta a Domingo das 11h00 às 22h00',
    main_image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    amenities: ['Taproom com 8 Torneiras', 'Tour pela Fábrica', 'Petiscos Alemães', 'Loja de Garrafas & Kits', 'Estacionamento'],
    tags: ['Cervejaria', 'Chope Artesanal', 'Quinta do Malte', 'Happy Hour', 'Mantiqueira'],
    rating: 4.8,
    review_count: 820,
  },
  {
    id: 'biz-socorro-7',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-gastronomia',
    name: 'Restaurante Saloon Caipira',
    slug: 'restaurante-saloon-caipira',
    description: 'O autêntico sabor da roça servido no tradicional fogão a lenha às margens do Rio do Peixe. Costela no bafo desmanchando, leitoa à pururuca crocante, feijão tropeiro, torresmo caipira e buffet de doces caseiros da fazenda.',
    address: 'Estrada Socorro / Munhoz, km 5,5 - Rio do Peixe, Socorro - SP',
    phone: '(19) 3895-7000',
    whatsapp: '5519993337000',
    instagram: 'salooncaipirasocorro',
    website: 'https://salooncaipira.com.br',
    latitude: -22.5921,
    longitude: -46.5305,
    price_min: 65,
    price_max: 140,
    opening_hours: 'Sexta a Domingo e Feriados: 11h30 às 16h30',
    main_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: false,
    is_premium: false,
    amenities: ['Buffet no Fogão a Lenha', 'Sobremesas Caseiras Inclusas', 'Vista para o Rio do Peixe', 'Espaço Kids'],
    tags: ['Comida Caipira', 'Fogão a Lenha', 'Costela no Bafo', 'Rio do Peixe', 'Almoço'],
    rating: 4.7,
    review_count: 670,
  },
  {
    id: 'biz-socorro-8',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-malhas',
    name: 'Circuito das Malhas Outlet Socorro',
    slug: 'circuito-das-malhas-outlet-socorro',
    description: 'O maior complexo comercial de moda tricô, malharia e couro direto da fábrica em Socorro. Mais de 50 lojas com coleções de outono/inverno, roupas masculinas, femininas e infantis a preços de atacado e varejo, praça de alimentação e amplo estacionamento.',
    address: 'Rodovia Deputado Antonio Silva Cunha Bueno, km 4 - Bairro Nogueiras, Socorro - SP',
    phone: '(19) 3895-8000',
    whatsapp: '5519992228000',
    instagram: 'circuitodasmalhas.socorro',
    website: 'https://circuitodasmalhas.com.br',
    latitude: -22.6012,
    longitude: -46.5054,
    price_min: 30,
    price_max: 350,
    opening_hours: 'Aberto diariamente das 09h00 às 18h30',
    main_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    amenities: ['Mais de 50 Lojas de Fábrica', 'Praça de Alimentação', 'Estacionamento Gratuito para Carros e Ônibus', 'Ar Condicionado'],
    tags: ['Malhas', 'Tricô', 'Compras', 'Preço de Fábrica', 'Moda Inverno'],
    rating: 4.6,
    review_count: 1450,
  },
  {
    id: 'biz-socorro-9',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-pousadas',
    name: 'Pousada Vale das Orquídeas',
    slug: 'pousada-vale-das-orquideas-socorro',
    description: 'Refúgio de charme encravado em um vale verdejante em Socorro. Chalés privativos com hidromassagem dupla com teto panorâmico de vidro, lareira a lenha, piscina com borda infinita para as montanhas e café da manhã colonial servido até o meio-dia.',
    address: 'Estrada Municipal da Pompeia, 1500 - Bairro da Pompeia, Socorro - SP',
    phone: '(19) 3895-9000',
    whatsapp: '5519991119000',
    instagram: 'valedasorquideassocorro',
    website: 'https://valedasorquideas.com.br',
    latitude: -22.6150,
    longitude: -46.5450,
    price_min: 420,
    price_max: 980,
    opening_hours: 'Check-in a partir das 14h / Check-out até às 12h',
    main_image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    amenities: ['Chalés com Hidro Dupla', 'Lareira a Lenha', 'Piscina com Borda Infinita', 'Café Colonial até 12h', 'Vista Panorâmica'],
    tags: ['Pousada Romântica', 'Casal', 'Hidromassagem', 'Montanha', 'Paz'],
    rating: 4.9,
    review_count: 430,
  },
  {
    id: 'biz-socorro-10',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-natureza',
    name: 'Mirante do Cristo Redentor de Socorro',
    slug: 'mirante-do-cristo-redentor-socorro',
    description: 'Monumento histórico e mirante no ponto mais alto da área urbana de Socorro. Do alto do mirante contempla-se toda a malha urbana histórica da cidade, as curvas do Rio do Peixe e as cadeias de montanhas da Serra da Mantiqueira.',
    address: 'Estrada do Cristo, s/n - Morro do Cristo, Socorro - SP',
    phone: '(19) 3895-1000',
    whatsapp: '5519998771000',
    instagram: 'turismosocorro',
    website: 'https://socorro.tur.br',
    latitude: -22.5980,
    longitude: -46.5210,
    price_min: 0,
    price_max: 0,
    opening_hours: 'Acesso livre diariamente',
    main_image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    amenities: ['Mirante Panorâmico', 'Estacionamento Gratuito', 'Empório de Artesanato', 'Acesso Pavimentado'],
    tags: ['Mirante', 'Cristo Redentor', 'Vista Panorâmica', 'Cartão Postal'],
    rating: 4.7,
    review_count: 910,
  },
];

export const SOCORRO_EXPERIENCES: Experience[] = [
  {
    id: 'exp-socorro-1',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-1',
    category_id: 'cat-socorro-aventura',
    name: 'Descida Radical de Rafting no Rio do Peixe',
    slug: 'descida-radical-rafting-rio-do-peixe-socorro',
    description: 'A aventura mais consagrada de Socorro. 4 a 7 km de descida pelas corredeiras de classe II a IV do Rio do Peixe a bordo de botes infláveis com guias especializados. Inclui salto da pedra, surf no bote e flutuação em águas calmas, com fotos em alta resolução.',
    price: 110,
    duration: '2h30 (na água)',
    main_image_url: '/images/socorro/aventura.webp',
    status: 'published',
    is_featured: true,
    included: [
      'Equipamentos homologados (colete, capacete e remo)',
      'Instrução de segurança pré-descida',
      'Guia profissional certificado em cada bote',
      'Uso dos vestiários com ducha quente e armários',
    ],
  },
  {
    id: 'exp-socorro-2',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-2',
    category_id: 'cat-socorro-natureza',
    name: 'Experiência Pôr do Sol & Pan de Palo na Pedra Bela Vista',
    slug: 'experiencia-por-do-sol-pan-de-palo-pedra-bela-vista',
    description: 'Viva o entardecer mais famoso do interior paulista no cume da Pedra Bela Vista a 1.250m de altitude. Aprecie o céu colorido pelas montanhas assando seu próprio Pan de Palo recheado na fogueira, com chope artesanal bem gelado e música ao vivo.',
    price: 60,
    duration: '3 horas',
    main_image_url: '/images/socorro/hero.webp',
    status: 'published',
    is_featured: true,
    included: [
      'Ingresso de acesso ao parque do mirante',
      '1 Pan de Palo artesanal para assar na brasa',
      '1 Chope artesanal ou bebida não alcoólica',
      'Acesso ao deck panorâmico e fogueira',
    ],
  },
  {
    id: 'exp-socorro-3',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-3',
    category_id: 'cat-socorro-natureza',
    name: 'Passeio de Pedalinho no Lago Cristalino da Gruta do Anjo',
    slug: 'passeio-pedalinho-gruta-do-anjo',
    description: 'Navegue pelas águas esmeraldas no interior de uma caverna com paredes rochosas esculpidas e formações minerais. Uma experiência única e refrescante para casais e famílias com crianças.',
    price: 45,
    duration: '1 hora',
    main_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    included: [
      'Entrada no Parque Ecológico da Gruta do Anjo',
      '30 minutos de passeio de pedalinho para até 2 pessoas',
      'Colete salva-vidas obrigatório',
      'Acesso às trilhas da mata ao redor',
    ],
  },
];

export const SOCORRO_ROUTES: Route[] = [
  {
    id: 'route-socorro-1',
    city_id: 'city-socorro',
    name: 'Circuito Aventura Total: Rafting, Monjolinho e Pôr do Sol na Bela Vista',
    slug: 'circuito-aventura-total-socorro',
    description: 'O roteiro definitivo de 1 dia para quem busca adrenalina e natureza exuberante em Socorro. Comece nas corredeiras do Rio do Peixe, almoce com comida caipira e finalize com o pôr do sol lendário na Pedra Bela Vista.',
    duration: '1 Dia Completo',
    profile: 'Aventura & Ecoturismo',
    image_url: '/images/socorro/aventura.webp',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'ri-soc-1-1',
        route_id: 'route-socorro-1',
        business_id: 'biz-socorro-1',
        title: '09h00 - Rafting no Rio do Peixe na Próxima Aventura',
        description: 'Descida nas corredeiras com muita adrenalina e banho de rio.',
        sort_order: 1,
      },
      {
        id: 'ri-soc-1-2',
        route_id: 'route-socorro-1',
        business_id: 'biz-socorro-7',
        title: '12h30 - Almoço no Fogão a Lenha no Saloon Caipira',
        description: 'Deliciosa costela no bafo e comida da fazenda servida à vontade.',
        sort_order: 2,
      },
      {
        id: 'ri-soc-1-3',
        route_id: 'route-socorro-1',
        business_id: 'biz-socorro-3',
        title: '15h00 - Passeio na Gruta do Anjo',
        description: 'Passeio refrescante de pedalinho no lago interior da gruta.',
        sort_order: 3,
      },
      {
        id: 'ri-soc-1-4',
        route_id: 'route-socorro-1',
        business_id: 'biz-socorro-2',
        title: '17h00 - Pôr do Sol e Pan de Palo na Pedra Bela Vista',
        description: 'Vista deslumbrante de 360°, fogueira e chope artesanal.',
        sort_order: 4,
      },
    ],
  },
  {
    id: 'route-socorro-2',
    city_id: 'city-socorro',
    name: 'Roteiro Compras de Malhas, Cervejarias e Gastronomia',
    slug: 'roteiro-compras-malhas-cervejarias-socorro',
    description: 'Itinerário relaxante para quem deseja renovar o guarda-roupa com malhas direto de fábrica e apreciar o melhor polo cervejeiro artesanal de Socorro.',
    duration: 'Tarde / Noite',
    profile: 'Compras & Gastronomia',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'ri-soc-2-1',
        route_id: 'route-socorro-2',
        business_id: 'biz-socorro-8',
        title: '14h00 - Compras no Circuito das Malhas Outlet',
        description: 'Compras de moda tricô e couro a preços de fábrica.',
        sort_order: 1,
      },
      {
        id: 'ri-soc-2-2',
        route_id: 'route-socorro-2',
        business_id: 'biz-socorro-6',
        title: '17h30 - Degustação de Chopes na Quinta do Malte',
        description: 'Tour pela fábrica e degustação de chopes artesanais da Mantiqueira.',
        sort_order: 2,
      },
    ],
  },
];

export const SOCORRO_EVENTS: EventItem[] = [
  {
    id: 'evt-socorro-1',
    city_id: 'city-socorro',
    name: 'Socorro MotoFest 2026 - Encontro Nacional de Motociclistas',
    title: 'Socorro MotoFest 2026 - Encontro Nacional de Motociclistas',
    slug: 'socorro-motofest-2026',
    description: 'Um dos maiores encontros de motociclistas do Brasil. Shows com bandas de classic rock, food trucks com gastronomia de rua, feira de acessórios para motociclismo, exposições de motos clássicas e customizadas no Centro de Eventos de Socorro.',
    event_date: '2026-08-21',
    start_date: '2026-08-21',
    end_date: '2026-08-23',
    event_time: 'Das 10h00 às 00h00',
    location: 'Centro de Exposições João Orlandi Pagliusi - Socorro - SP',
    image_url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'evt-socorro-2',
    city_id: 'city-socorro',
    name: 'Festival Gastronômico Sabores da Roça de Socorro',
    title: 'Festival Gastronômico Sabores da Roça de Socorro',
    slug: 'festival-gastronomico-sabores-da-roca-socorro-2026',
    description: 'Festival gastronômico que reúne os melhores restaurantes e produtores rurais de Socorro, apresentando pratos tradicionais caipiras, cachaças artesanais premiadas, queijos da Mantiqueira e doces de tacho ao som de moda de viola.',
    event_date: '2026-09-11',
    start_date: '2026-09-11',
    end_date: '2026-09-13',
    event_time: 'A partir das 12h00',
    location: 'Praça da Matriz - Centro Histórico, Socorro - SP',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
];
