import { City, Category, Business, Experience, Route, EventItem } from '@/types';

export const SOCORRO_CITY: City = {
  id: 'city-socorro',
  name: 'Socorro',
  slug: 'socorro',
  state: 'SP',
  country: 'Brasil',
  badge: 'Estância Hidromineral de Socorro - SP',
  subtitle: 'Capital da Aventura, Natureza e Ecoturismo.',
  description: 'Capital do turismo de aventura e do ecoturismo no Circuito das Águas Paulista. Famosa pelo rafting no Rio do Peixe, mirantes na Serra da Mantiqueira, gastronomia caipira, parques de aventura e compras de malhas.',
  tags: ['Aventura', 'Rafting', 'Natureza', 'Ecoturismo', 'Malhas'],
  image_url: '/images/socorro/hero.webp',
  hero_image: '/images/socorro/hero.webp',
  is_active: true,
};

export const SOCORRO_CATEGORIES: Category[] = [
  {
    id: 'cat-socorro-aventura',
    city_id: 'city-socorro',
    name: 'Aventura & Rafting',
    slug: 'aventura-rafting',
    description: 'Rafting no Rio do Peixe, tirolesas, arvorismo, quadriciclos, rapel e passeios 4x4.',
    icon: 'Compass',
    image_url: '/images/socorro/aventura.webp',
    is_active: true,
  },
  {
    id: 'cat-socorro-natureza',
    city_id: 'city-socorro',
    name: 'Natureza & Mirantes',
    slug: 'natureza-mirantes',
    description: 'Mirante Pedra Bela Vista, Gruta do Anjo, Mirante do Cristo e trilhas ecológicas.',
    icon: 'Mountain',
    image_url: '/images/socorro/hero.webp',
    is_active: true,
  },
  {
    id: 'cat-socorro-pousadas',
    city_id: 'city-socorro',
    name: 'Pousadas & Chalés',
    slug: 'pousadas-chales',
    description: 'Pousadas charmosas na serra, chalés rústicos com lareira e hidromassagem.',
    icon: 'Hotel',
    image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-gastronomia',
    city_id: 'city-socorro',
    name: 'Gastronomia Caipira',
    slug: 'gastronomia-caipira',
    description: 'Comida no fogão a lenha, leitão a pururuca, trutas frescas e churrasco de chão.',
    icon: 'Utensils',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-cafes',
    city_id: 'city-socorro',
    name: 'Cafés & Docerias',
    slug: 'cafes-docerias',
    description: 'Cafés da roça, doces caseiros, queijos artesanais da Mantiqueira e bolos no tacho.',
    icon: 'Coffee',
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-cervejarias',
    city_id: 'city-socorro',
    name: 'Cervejarias & Cachaças',
    slug: 'cervejarias-cachacas',
    description: 'Fábricas de cerveja artesanal, alambiques tradicionais e degustações guiadas.',
    icon: 'Beer',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-malhas',
    city_id: 'city-socorro',
    name: 'Compras & Malhas',
    slug: 'compras-malhas',
    description: 'Feira permanente de malhas, moda tricô de fábrica, couro e artesanato regional.',
    icon: 'ShoppingBag',
    image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
  {
    id: 'cat-socorro-hoteis-fazenda',
    city_id: 'city-socorro',
    name: 'Hotéis Fazenda',
    slug: 'hoteis-fazenda',
    description: 'Resorts rurais e hotéis fazenda premiados em acessibilidade, lazer e pensão completa.',
    icon: 'Trees',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    is_active: true,
  },
];

export const SOCORRO_BUSINESSES: Business[] = [
  {
    id: 'biz-socorro-1',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-aventura',
    name: 'Rio Abaixo Rafting & Aventura (DEMO)',
    slug: 'rio-abaixo-rafting-socorro-demo',
    description: 'Agência pioneira em rafting no Rio do Peixe, tirolesas e esportes de aventura com certificação de segurança e condutores experientes.',
    address: 'Estrada Socorro-Munhoz, Km 6 - Corredor Turístico do Rio do Peixe, Socorro - SP',
    phone: '(19) 3895-1000',
    whatsapp: '5519999911000',
    instagram: 'rioabaixo.socorro',
    website: 'https://rioabaixo.tur.br',
    latitude: -22.5901,
    longitude: -46.5298,
    price_min: 80,
    price_max: 200,
    opening_hours: 'Segunda a Domingo: 08:30 às 18:00',
    main_image_url: '/images/socorro/aventura.webp',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    amenities: ['Estacionamento', 'Vestiários', 'Equipamento de Segurança Incluso', 'Restaurante no Local', 'Pet Friendly'],
    tags: ['Aventura', 'Rafting', 'Rio do Peixe', 'Tirolesa', 'Destaque'],
    rating: 4.9,
    review_count: 142,
  },
  {
    id: 'biz-socorro-2',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-natureza',
    name: 'Mirante Pedra Bela Vista Bar & Ecoturismo (DEMO)',
    slug: 'mirante-pedra-bela-vista-socorro-demo',
    description: 'O ponto turístico mais famoso de Socorro. Mirante panorâmico no topo da serra com o lendário pôr do sol, fogueira e o autêntico Pan de Palo na brasa.',
    address: 'Estrada Municipal da Bela Vista, s/n - Bairro do Salto, Socorro - SP',
    phone: '(19) 3895-2000',
    whatsapp: '5519999912000',
    instagram: 'pedrabelavista.socorro',
    website: 'https://pedrabelavista.com.br',
    latitude: -22.6102,
    longitude: -46.5403,
    price_min: 40,
    price_max: 120,
    opening_hours: 'Quarta a Domingo: 12:00 às 21:00',
    main_image_url: '/images/socorro/hero.webp',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    amenities: ['Mirante Panorâmico', 'Bar & Gastronomia', 'Pan de Palo na Brasa', 'Trilhas de Rapel', 'Música ao Vivo'],
    tags: ['Mirante', 'Pôr do Sol', 'Pedra Bela Vista', 'Romântico', 'Pan de Palo'],
    rating: 4.9,
    review_count: 210,
  },
  {
    id: 'biz-socorro-3',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-natureza',
    name: 'Gruta do Anjo Parque Ecológico (DEMO)',
    slug: 'gruta-do-anjo-parque-ecologico-demo',
    description: 'Antiga mina de quartzo desativada que se transformou em uma caverna inundada deslumbrante, com passeios de pedalinho e piscina natural.',
    address: 'Estrada Socorro-Munhoz, Km 2,5 - Bairro da Lavra, Socorro - SP',
    phone: '(19) 3895-3000',
    whatsapp: '5519999913000',
    instagram: 'grutadoanjo.socorro',
    website: 'https://grutadoanjo.com.br',
    latitude: -22.5854,
    longitude: -46.5182,
    price_min: 35,
    price_max: 70,
    opening_hours: 'Terça a Domingo: 09:00 às 17:00',
    main_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    amenities: ['Passeio de Pedalinho', 'Lanchonete', 'Estacionamento', 'Fotografia', 'Natureza'],
    tags: ['Gruta do Anjo', 'Caverna', 'Pedalinho', 'Família', 'Passeio'],
    rating: 4.8,
    review_count: 98,
  },
  {
    id: 'biz-socorro-4',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-hoteis-fazenda',
    name: 'Parque dos Sonhos Hotel Fazenda & Ecoturismo (DEMO)',
    slug: 'parque-dos-sonhos-hotel-fazenda-demo',
    description: 'Complexo premiado internacionalmente pelo turismo acessível e sustentável, com tirolesas gigantes, passeios a cavalo, arvorismo e cachoeiras.',
    address: 'Estrada da Varginha, Km 7 - Limoeiro, Socorro - SP',
    phone: '(19) 3895-4000',
    whatsapp: '5519999914000',
    instagram: 'parquedossonhos.socorro',
    website: 'https://parquedossonhos.com.br',
    latitude: -22.5621,
    longitude: -46.4912,
    price_min: 150,
    price_max: 600,
    opening_hours: 'Aberto diariamente para day-use e hospedagem',
    main_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'premium',
    is_featured: true,
    is_premium: true,
    amenities: ['100% Acessível', 'Tirolesas', 'Passeios a Cavalo', 'Restaurante Incluso', 'Piscinas Naturais'],
    tags: ['Hotel Fazenda', 'Ecoturismo', 'Acessibilidade', 'Família', 'Tirolesa'],
    rating: 4.9,
    review_count: 175,
  },
  {
    id: 'biz-socorro-5',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-pousadas',
    name: 'Pousada Vale das Pedras Chalés (DEMO)',
    slug: 'pousada-vale-das-pedras-socorro-demo',
    description: 'Chalés privativos de alto padrão com hidromassagem, vista para as montanhas e café da manhã colonial servido na varanda.',
    address: 'Caminho Turístico do Rio do Peixe, Socorro - SP',
    phone: '(19) 3895-5000',
    whatsapp: '5519999915000',
    instagram: 'pousadavaledaspedras.socorro',
    website: 'https://valedaspedras.com.br',
    latitude: -22.5932,
    longitude: -46.5341,
    price_min: 350,
    price_max: 750,
    opening_hours: 'Check-in: 14:00 | Check-out: 12:00',
    main_image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    amenities: ['Hidromassagem', 'Piscina Climatizada', 'Café da Manhã Colonial', 'Wi-Fi Rápido', 'Vista Panorâmica'],
    tags: ['Pousada Romântica', 'Chalé', 'Casal', 'Mantiqueira', 'Tranquilidade'],
    rating: 4.8,
    review_count: 84,
  },
  {
    id: 'biz-socorro-6',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-gastronomia',
    name: 'Restaurante Fogão de Lenha Caipira (DEMO)',
    slug: 'restaurante-fogao-de-lenha-caipira-socorro-demo',
    description: 'O melhor da culinária tradicional paulista e mineira servida em panelas de barro no fogão a lenha, com sobremesas caseiras da fazenda.',
    address: 'Rodovia Capitão Bardoino, Km 132 - Socorro - SP',
    phone: '(19) 3895-6000',
    whatsapp: '5519999916000',
    instagram: 'fogaodelenha.socorro',
    website: 'https://fogaosocorro.com.br',
    latitude: -22.5802,
    longitude: -46.5120,
    price_min: 55,
    price_max: 110,
    opening_hours: 'Sexta a Domingo: 11:30 às 16:30',
    main_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    amenities: ['Fogão a Lenha', 'Espaço Kids', 'Sobremesas Caseiras', 'Estacionamento Amplo', 'Música Sertaneja Raiz'],
    tags: ['Comida Caipira', 'Fogão a Lenha', 'Gastronomia', 'Família', 'Feijoada'],
    rating: 4.8,
    review_count: 112,
  },
  {
    id: 'biz-socorro-7',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-cervejarias',
    name: 'Cervejaria Artesanal Quinta do Malte (DEMO)',
    slug: 'cervejaria-artesanal-quinta-do-malte-socorro-demo',
    description: 'Fábrica de cervejas artesanais premiadas no Circuito das Águas, com taproom rústico, petiscos artesanais e visitas guiadas pela fábrica.',
    address: 'Rodovia Pompeu Conti, 3230 - Bairro das Palmeiras, Socorro - SP',
    phone: '(19) 3895-7000',
    whatsapp: '5519999917000',
    instagram: 'quintadomalte.socorro',
    website: 'https://quintadomalte.com.br',
    latitude: -22.5975,
    longitude: -46.5198,
    price_min: 25,
    price_max: 85,
    opening_hours: 'Quinta a Domingo: 12:00 às 22:00',
    main_image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'highlight',
    is_featured: true,
    is_premium: false,
    amenities: ['Chopp Artesanal', 'Tour da Fábrica', 'Música ao Vivo', 'Pet Friendly', 'Área Externa'],
    tags: ['Cervejaria', 'Chopp Artesanal', 'Degustação', 'Noite', 'Happy Hour'],
    rating: 4.7,
    review_count: 73,
  },
  {
    id: 'biz-socorro-8',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-hoteis-fazenda',
    name: 'Hotel Fazenda Campo dos Sonhos (DEMO)',
    slug: 'hotel-fazenda-campo-dos-sonhos-demo',
    description: 'Referência pioneira em turismo rural pedagógico e ecoturismo acessível, com ordenha, cavalgadas, passeios de charrete e tirolesa.',
    address: 'Estrada dos Sonhos, Km 6 - Bairro da Lavra, Socorro - SP',
    phone: '(19) 3895-8000',
    whatsapp: '5519999918000',
    instagram: 'campodossonhos.socorro',
    website: 'https://campodossonhos.com.br',
    latitude: -22.5731,
    longitude: -46.5023,
    price_min: 200,
    price_max: 700,
    opening_hours: 'Aberto 24h para hóspedes | Day use: 09:00 às 17:00',
    main_image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    amenities: ['Turismo Rural', 'Piscina Coberta', 'Pensão Completa', 'Acessibilidade Total', 'Recreação Infantil'],
    tags: ['Hotel Fazenda', 'Crianças', 'Turismo Rural', 'Ecoturismo'],
    rating: 4.8,
    review_count: 65,
  },
  {
    id: 'biz-socorro-9',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-cafes',
    name: 'Café Colonial e Doceria da Mantiqueira (DEMO)',
    slug: 'cafe-colonial-doceria-mantiqueira-socorro-demo',
    description: 'Mesa farta de café colonial com pães caseiros, broas de milho, geleias artesanais, queijo meia cura e doces de leite premiados.',
    address: 'Rua Treze de Maio, 145 - Centro Histórico, Socorro - SP',
    phone: '(19) 3895-9000',
    whatsapp: '5519999919000',
    instagram: 'cafemantiqueira.socorro',
    website: 'https://cafesocorro.com.br',
    latitude: -22.5912,
    longitude: -46.5284,
    price_min: 20,
    price_max: 55,
    opening_hours: 'Terça a Domingo: 08:00 às 19:00',
    main_image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    amenities: ['Café Colonial', 'Doces Típicos', 'Queijos Artesanais', 'Ambiente Climatizado'],
    tags: ['Café Colonial', 'Doces', 'Queijos', 'Centro Histórico'],
    rating: 4.7,
    review_count: 53,
  },
  {
    id: 'biz-socorro-10',
    city_id: 'city-socorro',
    category_id: 'cat-socorro-malhas',
    name: 'Feira Permanente de Malhas de Socorro (DEMO)',
    slug: 'feira-permanente-de-malhas-socorro-demo',
    description: 'Mais de 50 lojas de fábrica reunidas no maior polo de compras de malhas, tricô, moda inverno, couro e artesanato do Circuito das Águas.',
    address: 'Rodovia Deputado Antonio Silva Cunha Bueno, Km 04 - Socorro - SP',
    phone: '(19) 3895-1010',
    whatsapp: '5519999911010',
    instagram: 'feirademalhas.socorro',
    website: 'https://feirademalhassocorro.com.br',
    latitude: -22.5841,
    longitude: -46.5210,
    price_min: 30,
    price_max: 300,
    opening_hours: 'Segunda a Domingo: 09:00 às 18:00',
    main_image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    plan: 'free',
    is_featured: false,
    is_premium: false,
    amenities: ['Estacionamento Gratuito', 'Praça de Alimentação', 'Preço de Fábrica', 'Acessibilidade'],
    tags: ['Compras', 'Malhas', 'Moda Tricô', 'Preço de Fábrica', 'Polo Têxtil'],
    rating: 4.6,
    review_count: 92,
  },
];

export const SOCORRO_EXPERIENCES: Experience[] = [
  {
    id: 'exp-socorro-1',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-1',
    category_id: 'cat-socorro-aventura',
    name: 'Descida de Rafting no Rio do Peixe',
    slug: 'descida-de-rafting-no-rio-do-peixe-socorro',
    description: 'Emoção pura descendo as corredeiras classe III e IV do Rio do Peixe com instrutores certificados, fotos profissionais e parada para banho de rio.',
    duration: '2h30min',
    price: 95,
    main_image_url: '/images/socorro/aventura.webp',
    status: 'published',
    is_featured: true,
    rating: 4.9,
    review_count: 98,
    included: ['Instruções de segurança', 'Colete salva-vidas e capacete homologados', 'Condutores certificados', 'Vestiários com ducha quente'],
  },
  {
    id: 'exp-socorro-2',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-2',
    category_id: 'cat-socorro-natureza',
    name: 'Pôr do Sol na Pedra Bela Vista com Pan de Palo',
    slug: 'por-do-sol-na-pedra-bela-vista-pan-de-palo-socorro',
    description: 'Assistir a um dos pores do sol mais famosos do Brasil a 1.250m de altitude com fogueira e o famoso pão assado na vara recheado na brasa.',
    duration: '3 horas',
    price: 45,
    main_image_url: '/images/socorro/hero.webp',
    status: 'published',
    is_featured: true,
    rating: 4.9,
    review_count: 145,
    included: ['Acesso exclusivo ao mirante panorâmico', '1 Pan de Palo tradicional doce ou salgado', 'Fogueira e música acústica'],
  },
  {
    id: 'exp-socorro-3',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-3',
    category_id: 'cat-socorro-natureza',
    name: 'Passeio de Pedalinho na Gruta do Anjo',
    slug: 'passeio-de-pedalinho-na-gruta-do-anjo-socorro',
    description: 'Navegação mágica pelo interior da gruta inundada em águas verde-esmeralda límpidas, com formações rochosas impressionantes.',
    duration: '1 hora',
    price: 40,
    main_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    rating: 4.8,
    review_count: 67,
    included: ['Entrada no parque ecológico', 'Passeio de pedalinho na caverna', 'Colete salva-vidas'],
  },
  {
    id: 'exp-socorro-4',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-4',
    category_id: 'cat-socorro-aventura',
    name: 'Mega Tirolesa Voadora no Parque de Aventura',
    slug: 'mega-tirolesa-voadora-parque-de-aventura-socorro',
    description: 'Voo inesquecível de 1km de extensão por cima do vale e das copas das árvores da Serra da Mantiqueira, em posição deitado estilo super-homem.',
    duration: '45 minutos',
    price: 110,
    main_image_url: '/images/socorro/aventura.webp',
    status: 'published',
    is_featured: true,
    rating: 4.9,
    review_count: 58,
    included: ['Equipamentos de voo duplo cabo', 'Instrutores especializados', 'Subida de van 4x4 até o ponto de salto'],
  },
  {
    id: 'exp-socorro-5',
    city_id: 'city-socorro',
    business_id: 'biz-socorro-7',
    category_id: 'cat-socorro-cervejarias',
    name: 'Degustação de Cervejas Artesanais e Queijos da Roça',
    slug: 'degustacao-cervejas-artesanais-queijos-socorro',
    description: 'Tour guiado pelos tanques de brassagem da cervejaria artesanal seguido de harmonização de 4 estilos de chopp com queijos curados da região.',
    duration: '1h30min',
    price: 70,
    main_image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
    rating: 4.8,
    review_count: 42,
    included: ['Visita técnica guiada com mestre cervejeiro', 'Régua de degustação com 4 estilos de cerveja', 'Tábua de queijos artesanais de Socorro'],
  },
];

export const SOCORRO_ROUTES: Route[] = [
  {
    id: 'route-socorro-1',
    city_id: 'city-socorro',
    name: 'Roteiro 1 Dia: Aventura Total & Rafting no Rio do Peixe',
    slug: 'roteiro-1-dia-aventura-total-socorro',
    description: 'O dia mais dinâmico de Socorro: rafting matinal nas corredeiras, almoço com comida no fogão a lenha e pôr do sol inesquecível na Pedra Bela Vista.',
    duration: '1 Dia Completo',
    profile: 'Amigos & Jovens',
    image_url: '/images/socorro/aventura.webp',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'item-socorro-1-1',
        route_id: 'route-socorro-1',
        business_id: 'biz-socorro-1',
        experience_id: 'exp-socorro-1',
        title: '09h00: Descida de Rafting no Rio do Peixe',
        description: 'Chegada ao Corredor Turístico, instruções e descida eletrizante pelas corredeiras.',
        sort_order: 1,
      },
      {
        id: 'item-socorro-1-2',
        route_id: 'route-socorro-1',
        business_id: 'biz-socorro-6',
        title: '12h30: Almoço Caipira no Fogão a Lenha',
        description: 'Banquete típico com comida da roça saborosa para repor as energias.',
        sort_order: 2,
      },
      {
        id: 'item-socorro-1-3',
        route_id: 'route-socorro-1',
        business_id: 'biz-socorro-2',
        experience_id: 'exp-socorro-2',
        title: '16h30: Pôr do Sol na Pedra Bela Vista & Pan de Palo',
        description: 'Subida ao topo da serra para assistir o pôr do sol ao som de música acústica e fogueira.',
        sort_order: 3,
      },
    ],
  },
  {
    id: 'route-socorro-2',
    city_id: 'city-socorro',
    name: 'Roteiro Fim de Semana Romântico na Serra',
    slug: 'roteiro-fim-de-semana-romantico-socorro',
    description: 'Hospedagem em chalé privativo com hidromassagem, mirantes panorâmicos, cafés artesanais e jantar intimista.',
    duration: '2 Dias (Sábado e Domingo)',
    profile: 'Casal',
    image_url: '/images/socorro/hero.webp',
    status: 'published',
    is_featured: true,
    items: [
      {
        id: 'item-socorro-2-1',
        route_id: 'route-socorro-2',
        business_id: 'biz-socorro-5',
        title: 'Sábado - Check-in no Chalé Vale das Pedras',
        description: 'Acomodação em chalé charmoso com vista para o vale.',
        sort_order: 1,
      },
      {
        id: 'item-socorro-2-2',
        route_id: 'route-socorro-2',
        business_id: 'biz-socorro-2',
        experience_id: 'exp-socorro-2',
        title: 'Sábado à tarde - Pôr do Sol & Pan de Palo',
        description: 'Tarde romântica no mirante mais alto de Socorro com lareira ao ar livre.',
        sort_order: 2,
      },
      {
        id: 'item-socorro-2-3',
        route_id: 'route-socorro-2',
        business_id: 'biz-socorro-7',
        title: 'Domingo - Degustação na Cervejaria Artesanal',
        description: 'Almoço leve com chopp especial antes da volta.',
        sort_order: 3,
      },
    ],
  },
  {
    id: 'route-socorro-3',
    city_id: 'city-socorro',
    name: 'Roteiro Família: Ecoturismo, Gruta do Anjo & Parques',
    slug: 'roteiro-familia-ecoturismo-socorro',
    description: 'Diversão garantida para todas as idades com passeios de pedalinho na caverna, tirolesas seguras e contato com animais de fazenda.',
    duration: '1 Dia Completo',
    profile: 'Família com Crianças',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'route-socorro-4',
    city_id: 'city-socorro',
    name: 'Roteiro Gastronomia Caipira, Cafés & Cachaças',
    slug: 'roteiro-gastronomia-caipira-socorro',
    description: 'Sabores autênticos do interior: doces de tacho, queijos artesanais, alambiques históricos e restaurantes de fazenda.',
    duration: '1 Dia Completo',
    profile: 'Família & Terceira Idade',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: false,
  },
  {
    id: 'route-socorro-5',
    city_id: 'city-socorro',
    name: 'Roteiro Compras de Malhas, Tricô & Mirante do Cristo',
    slug: 'roteiro-compras-malhas-mirante-socorro',
    description: 'Tour pelo polo têxtil com preços direto de fábrica na Feira de Malhas e visita ao Mirante do Cristo Redentor de Socorro.',
    duration: '1 Dia Completo',
    profile: 'Compras & Lazer',
    image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: false,
  },
];

export const SOCORRO_EVENTS: EventItem[] = [
  {
    id: 'evt-socorro-1',
    city_id: 'city-socorro',
    name: 'Festival de Inverno de Socorro (Socorro Luz & Som)',
    title: 'Festival de Inverno de Socorro (Socorro Luz & Som)',
    slug: 'festival-de-inverno-de-socorro',
    description: 'Música instrumental, jazz, blues, gastronomia de inverno e apresentações culturais nas praças e mirantes da cidade.',
    start_date: '2026-07-04',
    end_date: '2026-07-26',
    event_date: '2026-07-04',
    location: 'Praça da Matriz & Mirantes de Socorro',
    image_url: '/images/socorro/hero.webp',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'evt-socorro-2',
    city_id: 'city-socorro',
    name: 'Circuito Paulista de Rafting e Canoagem',
    title: 'Circuito Paulista de Rafting e Canoagem',
    slug: 'circuito-paulista-de-rafting-socorro',
    description: 'Competição com os melhores atletas do Brasil nas corredeiras do Rio do Peixe com workshops abertos para turistas.',
    start_date: '2026-09-12',
    end_date: '2026-09-13',
    event_date: '2026-09-12',
    location: 'Corredor Turístico do Rio do Peixe',
    image_url: '/images/socorro/aventura.webp',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'evt-socorro-3',
    city_id: 'city-socorro',
    name: 'Festival Gastronômico da Roça e Cachaça Artesanal',
    title: 'Festival Gastronômico da Roça e Cachaça Artesanal',
    slug: 'festival-gastronomico-da-roca-socorro',
    description: 'Chefs locais e produtores rurais apresentam pratos autorais feitos no fogão a lenha harmonizados com cachaças premiadas.',
    start_date: '2026-08-21',
    end_date: '2026-08-23',
    event_date: '2026-08-21',
    location: 'Centro de Exposições João Orlandi Pagliusi',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: true,
  },
  {
    id: 'evt-socorro-4',
    city_id: 'city-socorro',
    name: 'Encontro Nacional de Quadriciclos e 4x4 da Mantiqueira',
    title: 'Encontro Nacional de Quadriciclos e 4x4 da Mantiqueira',
    slug: 'encontro-nacional-quadriciclos-4x4-socorro',
    description: 'Trilha guiada pelas serras e estradas de terra históricas de Socorro com participantes de todo o Brasil.',
    start_date: '2026-10-10',
    end_date: '2026-10-12',
    event_date: '2026-10-10',
    location: 'Parque da Cidade de Socorro',
    image_url: '/images/socorro/aventura.webp',
    status: 'published',
    is_featured: false,
  },
  {
    id: 'evt-socorro-5',
    city_id: 'city-socorro',
    name: 'Mega Feira de Malhas & Tricô de Primavera',
    title: 'Mega Feira de Malhas & Tricô de Primavera',
    slug: 'mega-feira-de-malhas-primavera-socorro',
    description: 'Lançamento das novas coleções de moda tricô, malharia retilínea, moda praia e couro com descontos de fábrica.',
    start_date: '2026-09-18',
    end_date: '2026-09-27',
    event_date: '2026-09-18',
    location: 'Feira Permanente de Malhas de Socorro',
    image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    status: 'published',
    is_featured: false,
  },
];
